<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register an Application</name>
   <tag></tag>
   <elementGuidId>079794d4-37d9-42db-823f-e8c31ffdda7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sd18']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sd18</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>272b533e-113f-49a3-abe5-36699272c248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sd18</value>
      <webElementGuid>bcdb029d-b693-422e-9e04-db344a2b3c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>node</value>
      <webElementGuid>10ff7a8c-fa29-4575-a230-a7540e46b32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ControllerServlet?PAGE_ID=AREGA&amp;ACTION=Start&amp;ARDCMODE=ARREG</value>
      <webElementGuid>2935ce4e-0d06-4f20-a0d9-06b9d42af0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Register an Application</value>
      <webElementGuid>7cbe08b5-30d2-4965-a8e8-2ebd6493137f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>bodyframe</value>
      <webElementGuid>0748a438-3f90-468b-8683-f856948e518a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>window.status='Register an Application';return true;</value>
      <webElementGuid>55bd0ae6-136c-4c5c-a876-58c15e60768d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>window.status=''; return true;</value>
      <webElementGuid>857ce8a1-5907-4484-b99c-df492b29391f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript: d.s(18);</value>
      <webElementGuid>4c7787c6-13e3-4de1-a363-af133ecff821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register an   Application</value>
      <webElementGuid>757b88da-38d1-45d4-9dc8-4fde7372684c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sd18&quot;)</value>
      <webElementGuid>844803e8-2f4a-46c8-9508-3d112d39ac95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_This                         is an I_4f5493</value>
      <webElementGuid>f6a7307a-cfef-47f2-95b6-9be41b27cf51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sd18']</value>
      <webElementGuid>6d5e4bc3-c6dc-4da7-878a-9cc1cb42cee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dd17']/div/a</value>
      <webElementGuid>30e4aa68-e733-4127-9788-76b832346be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Registration'])[1]/following::a[1]</value>
      <webElementGuid>52616964-87c8-4133-9d16-a9203d8196e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register an']/parent::*</value>
      <webElementGuid>2f45644c-fbfa-43d5-9b5b-313f644cdb79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ControllerServlet?PAGE_ID=AREGA&amp;ACTION=Start&amp;ARDCMODE=ARREG')]</value>
      <webElementGuid>3c5ff0f6-987c-4aed-a396-24e44ee613dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/a</value>
      <webElementGuid>9ffc9873-5810-413c-9fbb-95984f6f5964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'sd18' and @href = '/ControllerServlet?PAGE_ID=AREGA&amp;ACTION=Start&amp;ARDCMODE=ARREG' and @title = 'Register an Application' and (text() = 'Register an   Application' or . = 'Register an   Application')]</value>
      <webElementGuid>4824940a-0bf0-4b0d-836b-91028cf6dacb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
