<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_TIERS Home</name>
   <tag></tag>
   <elementGuidId>74fa8259-7413-4443-860e-c49bb9281e6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sd0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sd0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a63297c-e5ac-447d-bf1e-6aebcddc294a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sd0</value>
      <webElementGuid>ae50aef8-f094-4381-8fa6-86380f8737e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>node</value>
      <webElementGuid>fd0ceef9-00fa-42a6-a35d-8d11f9fc12e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ControllerServlet?PAGE_ID=SELHP&amp;ACTION=loadHomePage</value>
      <webElementGuid>85b3554e-f0f7-43ce-b98c-25837f80c348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>TIERS Home</value>
      <webElementGuid>c59b18d2-bff2-478a-8850-cbc070bf921e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>bodyframe</value>
      <webElementGuid>c145d69c-e4ed-4e0d-b4c8-e7177cb55231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>window.status='TIERS Home';return true;</value>
      <webElementGuid>94dae821-770e-42d2-9ea4-5a29842d4d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>window.status=''; return true;</value>
      <webElementGuid>3935442a-7ac5-4cdb-a2b0-72a59500b8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TIERS Home</value>
      <webElementGuid>ea62d4c8-eada-4cc1-8fda-9d431d8fcacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sd0&quot;)</value>
      <webElementGuid>eeedf0c6-3ea7-4c7d-beba-316d2768dce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_This                         is an I_4f5493</value>
      <webElementGuid>2fc1c185-21e0-45f5-a715-f64c9d65c3ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sd0']</value>
      <webElementGuid>f27104f6-b6e0-44f9-acf6-a49ffffc9789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BRGLEFTAREA']/div/div/a</value>
      <webElementGuid>b5f189d5-0cc5-486d-8d9e-52c4a9aeb9c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'TIERS Home')]</value>
      <webElementGuid>c380fb3b-d81b-436c-bbbd-5b2fbe7616cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reception Log'])[1]/preceding::a[2]</value>
      <webElementGuid>93a5048c-2d59-4732-b883-18fbd7c2139b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TIERS Home']/parent::*</value>
      <webElementGuid>b8093085-411a-4536-9524-23c11a307177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ControllerServlet?PAGE_ID=SELHP&amp;ACTION=loadHomePage')]</value>
      <webElementGuid>934ff272-bf28-40d8-8588-a535cbe99a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>af13277d-19de-4d2e-b16f-f3638a411346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'sd0' and @href = '/ControllerServlet?PAGE_ID=SELHP&amp;ACTION=loadHomePage' and @title = 'TIERS Home' and (text() = 'TIERS Home' or . = 'TIERS Home')]</value>
      <webElementGuid>cec15807-2fd6-4f9f-9438-f7df9702c7d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
