<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_My Alerts_bodyframe</name>
   <tag></tag>
   <elementGuidId>ba963557-adb8-48ef-bf86-140eb871d1dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='bodyframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bodyframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2b7e7825-6132-4ea9-b911-ce06796d4f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bodyframe</value>
      <webElementGuid>8e42566f-aa61-4000-be1c-4248147e715b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bodyframe</value>
      <webElementGuid>ec23bc4d-92c4-4a03-9c4b-77cbfa94c38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/tiers/ControllerServlet?PAGE_ID=SELHP&amp;ACTION=loadHomePage</value>
      <webElementGuid>511c17cb-f584-434d-834a-6916382aaed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>1c0922fb-176d-4a5f-9295-ee6273e2e6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f5da46ed-e3b7-4c96-ac6a-8aa38eddf66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>13aaf39d-3a07-40dd-ba36-633d39b7bb10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d0622542-356a-4244-9f45-f4dd108389f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bodyIframe</value>
      <webElementGuid>7fe173e3-b118-4f56-8f16-cec65c89b89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Main</value>
      <webElementGuid>7368e8a8-12fc-4f8b-a30a-7a4e0d8182c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bodyframe&quot;)</value>
      <webElementGuid>dc020ea4-57ff-4b55-bc0e-32850f4cf477</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='bodyframe']</value>
      <webElementGuid>12d72398-4164-48be-ab5f-5bce4d0a909b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/iframe</value>
      <webElementGuid>13c87e6b-4b0a-4377-8f21-736ca75b9b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'bodyframe' and @name = 'bodyframe' and @src = '/tiers/ControllerServlet?PAGE_ID=SELHP&amp;ACTION=loadHomePage']</value>
      <webElementGuid>ff3c561c-6037-4920-8ff2-52a9cd1e4fc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
