<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_This                         is an I_4f5493</name>
   <tag></tag>
   <elementGuidId>ab220d25-a461-48ee-b381-cb9c438e578d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='nav']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5f44e122-4b2c-474e-a29f-b19f3a86ea2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>61c3fb35-4824-4409-8381-ba1e192a5085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>navigation</value>
      <webElementGuid>d65d1b90-31c4-4d0d-9e39-9e19fc9d6486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/tiers/LeftNavServlet</value>
      <webElementGuid>c93e0988-5378-4154-9fb4-bc1ce3b57a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>a23358f1-0fd6-45d3-a06d-d8061b410aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1cba15e7-48b0-48cf-9b15-b45e9ad524bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eb18f0ce-2104-43ef-878b-12f43843a913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>410ff309-ff93-402b-9eee-ec53bd74eade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navIframe</value>
      <webElementGuid>8fd8924d-18bb-4ad7-81a9-b03f5534120a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Navigation</value>
      <webElementGuid>7f0e2337-f21b-43eb-bc88-c36131553cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This 
                        is an IFRAME, you need to have Internet Explorer 4.0 or 
                        higher to see this.</value>
      <webElementGuid>651475c9-d66c-4882-a5cc-1b11b0ba21e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav&quot;)</value>
      <webElementGuid>41119a18-f837-4fba-9612-bd7e3749b72a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='nav']</value>
      <webElementGuid>031d1b4a-439e-4c78-b663-a8df6c416d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Alerts'])[1]/following::iframe[1]</value>
      <webElementGuid>42e60add-e81a-462f-a714-d0973224895a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Schedule'])[1]/following::iframe[1]</value>
      <webElementGuid>aff28c3c-12a2-4d27-baea-9fd2bc6c527a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'nav', '&quot;', ')')])[1]/preceding::iframe[3]</value>
      <webElementGuid>ff2f8521-da55-4d10-bc89-f14741cecf69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>1525c03f-39e0-4cc3-9292-2a675df7afb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'nav' and @name = 'navigation' and @src = '/tiers/LeftNavServlet' and (text() = 'This 
                        is an IFRAME, you need to have Internet Explorer 4.0 or 
                        higher to see this.' or . = 'This 
                        is an IFRAME, you need to have Internet Explorer 4.0 or 
                        higher to see this.')]</value>
      <webElementGuid>4b9e2d75-da13-4b03-b26a-cf9e4b3e3004</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
