<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_--_ssn1ssn</name>
   <tag></tag>
   <elementGuidId>0b9c4e20-7a2a-48c2-9c79-21b241fdef98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ssn1ssn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ssn1ssn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d483a87-0515-497b-8267-0df30e9b2b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ce701b7-2be3-4da3-be15-240fb6b75ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ssn1ssn</value>
      <webElementGuid>e7ff357d-33fa-408a-9215-9baab86ba0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ssn1ssn</value>
      <webElementGuid>4ba6c9ec-ca7f-4c8e-b44b-1d83b551cc2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>732cce75-c879-4e29-bd9a-86c8513f29a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d6a12f0e-cbb1-45c7-a4d1-19230176f538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>SSN</value>
      <webElementGuid>d14a5076-e1b6-44c2-af0d-ecf4e9a9c892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>SSN, three digit area number</value>
      <webElementGuid>aaa69263-78e6-4c15-bcf6-015bd901ee90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>ssn</value>
      <webElementGuid>985b3d92-69a3-46e9-9e48-ebfc71f4343f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>f60303d9-3764-4f33-aeb8-e19752b87211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form35</value>
      <webElementGuid>2904cbbb-b722-4a11-a327-538a0b255ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>setSelectFlagFalse()</value>
      <webElementGuid>7ab552f9-82f8-497b-9ec3-5e5df69178c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>advance(document.form1.ssn1ssn,document.form1.ssn2ssn)</value>
      <webElementGuid>a3a03201-a95e-4055-85dd-bd7ee1ce13b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ssaCheckbox('fromSSN');enableCreditSw(document.form1.scriptmode,document.form1.ssn1ssn,document.form1.ssn2ssn,document.form1.ssn3ssn,document.form1.reqDataBroker,document.form1.creditReportSw);ssaCheck(document.form1);</value>
      <webElementGuid>36514232-b189-4dd8-8418-cb0da58a78c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ssn1ssn&quot;)</value>
      <webElementGuid>018bc280-9326-4287-b0bd-8303c6e0d5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>be0f20ab-b9e0-476f-b588-06a0f4564036</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ssn1ssn']</value>
      <webElementGuid>002e8db6-6e96-4f97-8f9d-4325a3b86d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[4]</value>
      <webElementGuid>8eeb6f43-7a92-40b9-b90a-858525f24478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ssn1ssn' and @name = 'ssn1ssn']</value>
      <webElementGuid>a7c6a39b-e6f2-4e5e-ad6f-0526e39b502d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
