<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_--_ssn2ssn</name>
   <tag></tag>
   <elementGuidId>66d782b4-a120-4bc6-8e94-4e077b5ee71f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ssn2ssn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ssn2ssn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94d94054-1581-4d08-8447-6d2742fc590b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c489bd26-ddde-4ce5-87a3-6761b422106e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ssn2ssn</value>
      <webElementGuid>15e22b96-8c3f-4543-9c98-fbb3a09ddab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ssn2ssn</value>
      <webElementGuid>98fedbfa-e45a-43e9-983a-0d60ec7327fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e2089f95-8824-488f-8ab2-d0c318009933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>cdf54216-b626-438e-b025-4bc4b9715359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>SSN</value>
      <webElementGuid>b7feea19-f8f2-4294-982d-e2fdd23a8d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>SSN, two digit group number</value>
      <webElementGuid>256d3f0a-7791-479d-ae33-11b3b098bfdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>ssn</value>
      <webElementGuid>d22fa413-2f76-4357-8c26-ba5b5da0053d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>64521f65-96db-4aad-93d7-1297ed2fba72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form35</value>
      <webElementGuid>70adc541-8234-41fd-8ea7-6d23078f6d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>setSelectFlagFalse()</value>
      <webElementGuid>23ddc64b-c643-4492-b26b-81297d0d48de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>advance(document.form1.ssn2ssn,document.form1.ssn3ssn)</value>
      <webElementGuid>975c384f-d3f6-410f-800f-c8f784a4b4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ssaCheckbox('fromSSN');enableCreditSw(document.form1.scriptmode,document.form1.ssn1ssn,document.form1.ssn2ssn,document.form1.ssn3ssn,document.form1.reqDataBroker,document.form1.creditReportSw);ssaCheck(document.form1);</value>
      <webElementGuid>2f652562-1971-4910-8b94-c61f24115d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ssn2ssn&quot;)</value>
      <webElementGuid>c6ceace7-0358-4360-ac01-79abd47fbf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>ed56a85e-95de-421d-aa25-f1e7502832c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ssn2ssn']</value>
      <webElementGuid>9feb39b5-4d74-4805-9944-e0c6a01be61d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[5]</value>
      <webElementGuid>60301058-fae8-402a-a168-2af8864b98a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ssn2ssn' and @id = 'ssn2ssn']</value>
      <webElementGuid>5eb343fd-4374-4e52-98e3-774d8e384178</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
