<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__monthdateReceived</name>
   <tag></tag>
   <elementGuidId>9290c7c9-d380-48a9-9872-78bc3207ebaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='monthdateReceived']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#monthdateReceived</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffaa12eb-ff99-4a74-8f8b-77fc88378123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Date Received, two digit month</value>
      <webElementGuid>404c1362-6b76-4be6-9b2d-12c702fe5ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34b20688-ba7a-4c48-bf57-9e3996064a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>monthdateReceived</value>
      <webElementGuid>1925edf3-d4ee-4687-ad11-ad22b1d597b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>monthdateReceived</value>
      <webElementGuid>7cc9960b-aebf-4ccc-923a-66f0cdb940d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>mm</value>
      <webElementGuid>80458211-00b9-4e9c-95cd-b2d0d3dd0bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm</value>
      <webElementGuid>0d80fe51-1e20-41e2-8a59-1b50ac2c44b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2345e352-cd3c-44f8-87ab-bbbad2a7e5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>394ebf90-5465-4359-b3e2-0d93713e6416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>Date Received</value>
      <webElementGuid>d89eb3ca-bfdb-4501-90be-01df8994fcee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>dateReceived</value>
      <webElementGuid>2f76edfe-0d3c-4a8b-9f01-d92d4c6b0d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e95905fa-e34d-4808-afa5-6119c356a455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>setSelectFlag()</value>
      <webElementGuid>d5db0f8b-1f33-42bc-a300-66c0fc8ea011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form35</value>
      <webElementGuid>071c8086-46f2-4ff7-a37f-79316027347a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>clearMonthDayYear(document.form1.monthdateReceived);  advance(document.form1.monthdateReceived,document.form1.datedateReceived)</value>
      <webElementGuid>5e0868f9-dcaf-4449-94f8-43dbb3eaaf21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;monthdateReceived&quot;)</value>
      <webElementGuid>eef81397-3353-4786-a2a0-95e2a1fc7f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>678ad60b-0c36-4436-9690-3ce04a190daf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='monthdateReceived']</value>
      <webElementGuid>730fa2b9-b97c-481a-95f6-1437bc7fd8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>0810165e-d699-49e8-b73e-0a8b4b0e4b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'monthdateReceived' and @name = 'monthdateReceived' and @placeholder = 'mm']</value>
      <webElementGuid>32f53078-11a6-4f1d-ab45-f778926f5a5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
