<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__priorMedicaid_0</name>
   <tag></tag>
   <elementGuidId>e2d58572-34c2-4680-8f7b-2f5bb2ac30be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='priorMedicaid_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#priorMedicaid_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00931b75-f498-4002-86f1-24da67b0cf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>CHECKBOX</value>
      <webElementGuid>374ff04f-5465-48ec-8f7f-edc7c8b14283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>priorMedicaid_0</value>
      <webElementGuid>62002754-b04a-4def-ba6c-2a324347567a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>68d55497-59de-4de2-89a1-c0dd1ac79fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>bfbcf6bf-395b-4443-aec4-4278246b56b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>priorMedicaid_0</value>
      <webElementGuid>f654b63b-2e50-4f8f-8b2c-8f8736e04760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form35</value>
      <webElementGuid>1ca03596-585e-40ca-a2c3-174ad0c90d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>Ongoing/Prior Months Coverage</value>
      <webElementGuid>dbc18e14-f8de-4156-bf9a-a24497da901f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Ongoing/Prior Months Coverage</value>
      <webElementGuid>c32bbff1-08bd-4da8-b53f-7ee9eb2811ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>priorMedicaid</value>
      <webElementGuid>b2c89cd9-bd93-4f9d-ad14-a66711521b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;priorMedicaid_0&quot;)</value>
      <webElementGuid>e81036a8-e381-4f7b-90e3-8c88a7c29e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>ad6793fe-5d0b-4f60-819a-f97a1ce83307</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='priorMedicaid_0']</value>
      <webElementGuid>050ae090-45ca-4e5d-be93-af98a652885c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/table/tbody/tr/td/input</value>
      <webElementGuid>2fdf4340-13ba-4739-8374-24e4b37d738c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'CHECKBOX' and @name = 'priorMedicaid_0' and @id = 'priorMedicaid_0']</value>
      <webElementGuid>9cc57bd1-1fdb-4f90-ae98-00d635b0701c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
