<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__monthdateOfBirth</name>
   <tag></tag>
   <elementGuidId>e56123ce-fabb-4130-bb70-78f24d9f09d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='monthdateOfBirth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#monthdateOfBirth</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78c88959-5cb8-45de-bf40-6d1aeb4a98d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Date of Birth, two digit month</value>
      <webElementGuid>af01dba3-ca06-4d65-8940-61ff263d5d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23d4d128-3cdc-41b4-b3fe-ed373b4d6542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>monthdateOfBirth</value>
      <webElementGuid>65fe3527-a32a-4b15-90b6-e7a44ca40c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>monthdateOfBirth</value>
      <webElementGuid>3492dc69-be47-4769-b3f3-a38e8ad33385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>mm</value>
      <webElementGuid>885819d3-6be2-4419-a2c7-54a43e854674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm</value>
      <webElementGuid>6ce2fb15-6f90-477b-a345-f43a3a64a74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b2f4408b-985c-4c1a-a84c-e0056e671476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>91ffeb74-a09f-4630-8375-e80fd13e84ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>Date of Birth</value>
      <webElementGuid>a1f7039e-4d89-44ae-a3f7-6ec8b59fc83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>dateOfBirth</value>
      <webElementGuid>0d4d9f04-23ee-4435-8826-85325b5ce5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>94e2e539-d42f-4be3-960f-ae443de59f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>setSelectFlag()</value>
      <webElementGuid>cb424596-b1c4-426a-8a0b-d23ae7cfcacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form35</value>
      <webElementGuid>a4289d6e-d92f-403c-aab5-f94b6e241726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>clearMonthDayYear(document.form1.monthdateOfBirth);  advance(document.form1.monthdateOfBirth,document.form1.datedateOfBirth)</value>
      <webElementGuid>3f117924-5dc7-43eb-b078-387045c8c05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>populateSSNMonYear();</value>
      <webElementGuid>acf869a1-5449-416c-b621-805fbaf46611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>changeDOBOnlyOnceVal();</value>
      <webElementGuid>9772de0e-8d18-47f1-a5cc-137af2ee1b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;monthdateOfBirth&quot;)</value>
      <webElementGuid>0b584828-1999-4e49-80e5-ccc13507eb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>dee7502a-4018-444b-83fa-1b5e5a128a64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='monthdateOfBirth']</value>
      <webElementGuid>b6b2db0a-74f6-49a5-a97a-5df6fddcf9ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[14]/tbody/tr/td[4]/input</value>
      <webElementGuid>1c35e2cc-0038-4510-8ecd-82e158d41bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'monthdateOfBirth' and @name = 'monthdateOfBirth' and @placeholder = 'mm']</value>
      <webElementGuid>f86202ad-0216-4fa7-81a9-5f55a4c1c4d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
