<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Male_fileClearance</name>
   <tag></tag>
   <elementGuidId>b0f1214d-53ec-4874-83d0-e7ab1b2f4581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='fileClearance']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;fileClearance&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d76e746-e22e-4740-bbde-ab686ed5b201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>091260f4-7db9-4f02-abe1-46a60d7b559f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>fc</value>
      <webElementGuid>563f4c7a-6371-44d4-ab93-9b37543c6c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fileClearance</value>
      <webElementGuid>ab22ab91-1951-44b8-8746-49ece1c46550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>72c7d489-f470-4ef4-bd43-007fdfb5d511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>document.form1.fileClearId.value=document.form1.checkfile0.value;document.form1.isHohSw.value=document.form1.isHSw0.value;</value>
      <webElementGuid>f39aae4f-a685-467e-a29c-d213cb0c9586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>File Clearance</value>
      <webElementGuid>874dad09-a70b-48cc-b56f-56a972e09dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HouseholdSummary&quot;)/tbody[1]/tr[1]/td[9]/input[1]</value>
      <webElementGuid>799f0325-7fc3-4c75-855e-61b05927befb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>18e0b2a2-bca1-482e-8bde-d55d2721cf46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='fileClearance']</value>
      <webElementGuid>d02e0f38-7947-4237-9257-17acfe1ff0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='HouseholdSummary']/tbody/tr/td[9]/input</value>
      <webElementGuid>b79fe360-9314-4d57-8f36-8a52e7824d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/input</value>
      <webElementGuid>73a676c2-d664-4163-8320-8053d9501fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'fileClearance']</value>
      <webElementGuid>58c1ba22-d525-4623-b09d-82965226b26c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
