<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Medicaid_ltc</name>
   <tag></tag>
   <elementGuidId>b948ac2e-9744-4cd1-9f1d-749bddf0b9d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ltc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ltc&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79ed4c3e-b40d-4c82-b756-d0a61f3db7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>39893639-544f-4c59-bc70-818e8228e6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ltc</value>
      <webElementGuid>578bf049-0e99-4097-8234-3d69bb81797c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>MA</value>
      <webElementGuid>f1a5febe-1bdc-47e2-afb5-e81ba13831b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e4435ad0-584c-4c0c-acd7-75bdba908cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:checkARRPRProgram(this);enableDisableIndvAttributesAr();enableDisableIndvMedicaid();selValLtc(this);checkMBICVal();</value>
      <webElementGuid>f2821afb-2ea6-4ef9-9238-cd3a5e30c857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Medicaid</value>
      <webElementGuid>88861145-e828-4e4c-b548-87dce1c053a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[2]/tbody[1]/tr[2]/td[3]/table[@class=&quot;bodyFormLabels&quot;]/tbody[1]/tr[1]/td[3]/input[1]</value>
      <webElementGuid>25bdcfd9-55a4-40dd-9c65-205531c8b082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>f23aa5c9-dc49-42e3-913f-29d7921bb27b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ltc']</value>
      <webElementGuid>a8dd2df9-2d99-446f-8c91-a9c29343ff81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>833b6243-47c2-44a0-9905-2855554ff38b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'ltc']</value>
      <webElementGuid>5194e24c-7e50-463a-b0c2-210a44c45bd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
