<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Applicable Forms_button3</name>
   <tag></tag>
   <elementGuidId>6e5fd68e-56e9-495e-aeec-f852183f8fed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='button3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3778df4a-a594-4e5f-bea9-ab8823013cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>IMAGE</value>
      <webElementGuid>1ab27c57-ffcc-4fe6-8aff-d26e1f9fa33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button3</value>
      <webElementGuid>8ea26e28-a834-4765-a8ac-49a116b3e66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>101</value>
      <webElementGuid>e8b9c338-27a3-4ea2-a6b5-5dc04d9b63da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button3</value>
      <webElementGuid>26e70c93-c4af-451e-85a4-1df604f55215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/tiers/images/buttonSubmit.gif</value>
      <webElementGuid>d2bc13b5-640f-4fee-88dd-03ac428ab344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Click to Submit.</value>
      <webElementGuid>c7cc4b6a-5742-4266-ad0a-91da3591731b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5553f550-f98f-4fa4-8e90-63753cb1908f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>d2b45661-5ed7-408c-82e5-8a938f62a47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setSubmitTarget();return false;</value>
      <webElementGuid>bf8f8d82-e944-4f35-8196-0483a89de957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click to Submit.</value>
      <webElementGuid>b3e8faae-8a37-4338-be72-c2f0b0e1da39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button3&quot;)</value>
      <webElementGuid>68e12e32-7893-46bd-a4ce-758e0fdc5ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>e115aa05-5936-4e0d-ab75-1dfd2587d5b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='button3']</value>
      <webElementGuid>7c929d21-0532-4107-8322-7b5d38720305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[24]/tbody/tr/td/div/input[3]</value>
      <webElementGuid>d0aa5318-c1ec-44bd-a062-5ba1b6187395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'IMAGE' and @id = 'button3' and @name = 'button3' and @src = '/tiers/images/buttonSubmit.gif' and @alt = 'Click to Submit.' and @title = 'Click to Submit.']</value>
      <webElementGuid>167f663d-c824-4805-8d2a-9997a346f26d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
