<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail address_actionButton4</name>
   <tag></tag>
   <elementGuidId>d2fe2151-9ea9-41cb-b166-a02f4202f90f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='button4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f8e66ca-b7f1-4fc3-8ded-ea59e571dd02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>IMAGE</value>
      <webElementGuid>20588b53-9e70-4267-9ef4-0d7c44a48783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button4</value>
      <webElementGuid>70ff8250-6994-466f-8a0a-655cab7a93d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>a59be332-11fb-4555-bc10-ab01a2c3281f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actionButton4</value>
      <webElementGuid>6ae3ff75-37b8-4e4f-905d-c39977451236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/tiers/images/buttonNext.gif</value>
      <webElementGuid>56d0e740-1694-4cec-8c74-00c7e45d7465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Click to go to the next page.</value>
      <webElementGuid>74b74787-77db-49c1-ab1d-8558b2f0533d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f2817eab-3451-4edd-ad3f-ba35dfc11a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>51cc8e33-182e-4c97-b74d-870762dc538e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setActionFieldAndSubmit(document.form1,'Next','Y');return false;</value>
      <webElementGuid>e0d5b0c7-4520-4e69-935e-ebec82a1e2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click to go to the next page.</value>
      <webElementGuid>efd0851b-8c03-47c0-8351-387abc5b3006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button4&quot;)</value>
      <webElementGuid>0d18b3f5-d635-4a38-a097-dbbd2f659d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>82176ccb-cb5e-46dd-8284-ac92e47de089</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='button4']</value>
      <webElementGuid>e7301b96-bc0f-481b-b678-78b693441875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[28]/tbody/tr/td/div/input[6]</value>
      <webElementGuid>45c0508a-ccca-407f-9c53-e0601d59ecce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'IMAGE' and @id = 'button4' and @name = 'actionButton4' and @src = '/tiers/images/buttonNext.gif' and @alt = 'Click to go to the next page.' and @title = 'Click to go to the next page.']</value>
      <webElementGuid>9ee81f5b-6e17-4567-90de-ea4572848e36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
