<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Case or Application_caseOrApplicationNumber</name>
   <tag></tag>
   <elementGuidId>def729a8-5ff1-4458-bb78-14ef17e6ba00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='caseOrApplicationNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#caseOrApplicationNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee29da37-c538-45d9-8fce-4b13a922cedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85c0b811-f477-43cb-94b5-4cea93cddabf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>caseOrApplicationNumber</value>
      <webElementGuid>752029c8-6338-4b4a-9d40-5f5ab8f3f0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>a5d6f5c0-9712-408f-b3c9-90ca549ec74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>53421e7e-a63a-462c-bce1-89854cbd5683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>caseOrApplicationNumber</value>
      <webElementGuid>1c31eec7-db68-4ae4-bf3b-749d40e3bfd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1049991331</value>
      <webElementGuid>d0e0b72a-0cbb-4b44-be84-949df7429c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form150</value>
      <webElementGuid>e0070c16-e379-4b3d-b600-4041a979816a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>Case or Application #</value>
      <webElementGuid>653b3c3e-e4ba-446b-b758-db856fe507fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Case or Application #</value>
      <webElementGuid>27ff42b0-f839-48f1-bd3b-b34e642018ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>caseOrApplicationNumber</value>
      <webElementGuid>2a96266b-d0ba-4d09-9d2a-181e0a5e37bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>isCaseNumber(document.form1.caseOrApplicationNumber); isAppNumber(document.form1.caseOrApplicationNumber,document.form1.interviewMode);checkCaseflow();</value>
      <webElementGuid>0e036733-1cae-45eb-b284-f34244c47ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;caseOrApplicationNumber&quot;)</value>
      <webElementGuid>2a2450ba-f37c-4d1f-9bc6-a14ab418e9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>c493f8e2-f60f-45a1-a9aa-8272b0d8a4ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='caseOrApplicationNumber']</value>
      <webElementGuid>2527f785-8812-4eb8-84d4-5444540cbaa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>bac9b80e-0056-4bd3-af94-1b3b26f6a6a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'caseOrApplicationNumber' and @id = 'caseOrApplicationNumber']</value>
      <webElementGuid>a28892ef-3817-4d94-af35-61853000b206</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
