<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dynaLocalSubmitButton</name>
   <tag></tag>
   <elementGuidId>ce00de43-2bd0-41f8-843e-5224291d6bbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dynaLocalSubmitButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dynaLocalSubmitButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9ab0085-0704-44b3-ad66-da7bfe3c214f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>IMAGE</value>
      <webElementGuid>6fe281c2-8496-4f10-acc3-24fcbdcb07d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dynaLocalSubmitButton</value>
      <webElementGuid>368ab39e-dc11-410f-945e-f3f1f323c28a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>98</value>
      <webElementGuid>2699109b-fa22-4724-ba36-e437c7fb63e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/tiers/images/buttonAdd.gif</value>
      <webElementGuid>0caa7528-59f0-4d04-a085-67a03fc40279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Click to Add another record.</value>
      <webElementGuid>81593ecb-0792-4243-9c22-e224f9208fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:saveToDynaLocal(this.form);return false</value>
      <webElementGuid>e7aed055-26be-47ad-bb1a-8320d88ee61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b81376b3-5e7d-4d47-b0c5-364c3fef3ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>198fc771-af28-465f-b254-81c4884a72ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click to Add another record.</value>
      <webElementGuid>d698934d-1fec-4515-aa58-90601f614553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dynaLocalSubmitButton&quot;)</value>
      <webElementGuid>7747cd53-d50c-45fa-bd2c-65baa57f9e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>6c416847-31a8-4e0f-bb64-49ce86eeaced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dynaLocalSubmitButton']</value>
      <webElementGuid>e54cefd9-62cf-4b67-96c3-d84723d8d7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[15]/tbody/tr/td/div/input[2]</value>
      <webElementGuid>dab747d4-4adb-4586-bf60-c818bf0d2e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'IMAGE' and @id = 'dynaLocalSubmitButton' and @src = '/tiers/images/buttonAdd.gif' and @alt = 'Click to Add another record.' and @title = 'Click to Add another record.']</value>
      <webElementGuid>dbefb861-f91f-41a4-a194-39b77a20a2e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
