<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TANF_txw</name>
   <tag></tag>
   <elementGuidId>35a9adc6-d6fc-4236-a4e8-d5a7b56c52f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='txw']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;txw&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5800d785-8c09-4cbf-bc61-e38509ee5d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a169dd94-4984-4b64-98ea-4ab7ee116113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txw</value>
      <webElementGuid>0eb78bac-3f6e-46f3-9739-7c8931566259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TF</value>
      <webElementGuid>5ab573e7-ebd4-4174-8919-a29de3419968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e1187fe3-4049-44e8-9107-7acc4dc85309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>enableDisableIndvAttributesAr();enableDisableIndvMedicaid();checkMBICVal();</value>
      <webElementGuid>e3d38342-7826-4681-ac61-1a3a342253f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>TANF</value>
      <webElementGuid>b7d41f3f-3060-45d2-90a9-a720e2dbe594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[2]/tbody[1]/tr[2]/td[3]/table[@class=&quot;bodyFormLabels&quot;]/tbody[1]/tr[1]/td[1]/input[1]</value>
      <webElementGuid>499c770d-1bd1-4065-9788-ea6cb146acd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>25d49ac9-69f4-4fc5-99c8-1a5990bf32df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='txw']</value>
      <webElementGuid>b3e09f75-425c-4fdd-8cf4-3ba868ba890e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>b942a8f1-3baa-4f89-b1be-a39ed1aac2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'txw']</value>
      <webElementGuid>0409961c-1a91-4160-955f-293541790406</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
