<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Male_actionButton2</name>
   <tag></tag>
   <elementGuidId>02f87ebf-178f-4d25-854c-8b6b5bd0c2ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='button2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abe1ba9c-2422-48f2-af80-b437f8831301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>IMAGE</value>
      <webElementGuid>df1ab3b8-83bf-4879-b4e3-82c45da1020e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button2</value>
      <webElementGuid>ef4137be-9be2-467d-874e-2251be88f115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>102</value>
      <webElementGuid>b6114f78-f496-483e-b113-6c0c4fb1fe25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actionButton2</value>
      <webElementGuid>b94bfb72-dc39-471f-8dd7-366b07ce5534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/tiers/images/buttonFileClearance.gif</value>
      <webElementGuid>ef5e6012-469d-4881-ac93-a3a4436c5c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>File Clearance.</value>
      <webElementGuid>f53aaf54-1637-4878-917d-f3c3293988dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a9144a0a-9f97-450c-983b-6c3d74554041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>File Clearance</value>
      <webElementGuid>9bfd7d0e-97e8-4d17-9e5e-15cee8e2dea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(checkIndvsExist(document.form1,'FileClearance') &amp;&amp; checkFileClicked(document.form1,'FileClearance')){document.form1.PAGE_ID.value='ARTFC';setActionFieldAndSubmit(document.form1,'FileClearance','Y');}return false;</value>
      <webElementGuid>784a9901-985d-4e62-980e-e4fb4c7677fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>File Clearance.</value>
      <webElementGuid>9fe316f0-6f3f-4073-8d98-8e557a9d08e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button2&quot;)</value>
      <webElementGuid>15dfc733-7bb8-4177-ae1a-6cccc155af59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>c1d72475-f01a-47a0-97cb-05e457259291</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='button2']</value>
      <webElementGuid>5f60a0df-d28d-4df1-930b-048846dfad8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[11]/tbody/tr/td/div/input[2]</value>
      <webElementGuid>5673f05b-7bbe-4954-87f1-ccc9f8f9bb1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'IMAGE' and @id = 'button2' and @name = 'actionButton2' and @src = '/tiers/images/buttonFileClearance.gif' and @alt = 'File Clearance.' and @title = 'File Clearance.']</value>
      <webElementGuid>e4ea40c8-d5a4-4069-acbf-a88195d27336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
