<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MAGI_mag</name>
   <tag></tag>
   <elementGuidId>85241d69-9b04-4fa4-8814-5990354ed8e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='mag']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;mag&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>249a9e54-af07-4e9e-a879-bfcda93b7a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7314b96d-70a2-4d44-a07a-9b35d2fbb8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mag</value>
      <webElementGuid>1dfd1196-0e27-4fdd-909b-c5cc6e3abf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>MG</value>
      <webElementGuid>4340f5e7-79a7-4e2d-a0d4-00746ff10946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>9f2229be-d417-4791-bf4e-4269a8e50d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setSubProgCd();validateSubProgType();enableDisableIndvAttributesAr();enableDisableIndvMedicaid();checkMBICVal();</value>
      <webElementGuid>0e6c4b36-5e49-474f-89c2-61dcd418f72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>MAGI</value>
      <webElementGuid>afa0af38-7491-4c7d-aa86-e26cc0bd22c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[2]/tbody[1]/tr[2]/td[3]/table[@class=&quot;bodyFormLabels&quot;]/tbody[1]/tr[1]/td[5]/input[1]</value>
      <webElementGuid>b2d6ab48-b378-41fe-b52c-64f9d5e4bc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>5f963a47-453c-445f-98f0-ce94e574c969</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='mag']</value>
      <webElementGuid>e872b10c-dda8-4d73-a775-a649b2f161d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>3b08060b-40d5-48d4-964b-b4973859815c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'mag']</value>
      <webElementGuid>e26393f8-a879-464a-a72d-43c721c81cb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
