<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__yeardateOfBirth</name>
   <tag></tag>
   <elementGuidId>13138550-426c-4143-bfe6-adc77cc88a60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='yeardateOfBirth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#yeardateOfBirth</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40345bbd-e663-4bb3-8960-6e5cd67e60ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Date of Birth, four digit year</value>
      <webElementGuid>83c5f2fe-94cb-4f27-b853-f919fa17cbe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e36d525-7f7f-4397-a718-8cefcdeb0ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>yeardateOfBirth</value>
      <webElementGuid>918a2c8a-f9d3-46c3-ae8c-f7cf6dd53212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yeardateOfBirth</value>
      <webElementGuid>e57edf7f-c9a0-4f37-9565-086a2343bfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>yyyy</value>
      <webElementGuid>1dfa1552-369a-40c2-a0d6-6e2948246d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy</value>
      <webElementGuid>32a806a9-974f-4165-987b-527f6a519304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4a6e7925-4cf6-4e9d-ab06-32c3f65cc266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>88ec1bfb-f086-49f7-a376-e90b737d7a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>Date of Birth</value>
      <webElementGuid>29f9724e-0e3d-4948-a630-95f8c8f84427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>dateOfBirth</value>
      <webElementGuid>d6f4c528-8ca1-4830-8fad-2d6a57390b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>842824a8-c51f-47fd-a414-6a55b4c9747b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form35 hasDatepicker</value>
      <webElementGuid>8f7406e7-6caa-4a79-8846-5ad223dccc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onselect</name>
      <type>Main</type>
      <value>setSelectFlag()</value>
      <webElementGuid>2c9d568a-a1b7-476c-a33c-0eaaab347491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>clearMonthDayYear(document.form1.yeardateOfBirth)</value>
      <webElementGuid>0796bd03-8a7a-4852-9c7b-52424a4c0c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>computeAge(document.form1.monthdateOfBirth,document.form1.datedateOfBirth,document.form1.yeardateOfBirth,'120');futureDate(document.form1.monthdateOfBirth,document.form1.datedateOfBirth,document.form1.yeardateOfBirth,document.form1.dateOfBirth)</value>
      <webElementGuid>26be2d80-fdb4-4b0e-b714-24f0df6fa453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>populateSSNMonYear();</value>
      <webElementGuid>9d8537a2-ecc4-4f4d-8fdb-d4f5f2bb5c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yeardateOfBirth&quot;)</value>
      <webElementGuid>a876352d-8cdf-41d4-87e1-da63c882a549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>0d6a1b20-b531-4e99-80bc-4d8d413592e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='yeardateOfBirth']</value>
      <webElementGuid>1c008bcf-f294-4706-ae04-67dc0100c6d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input[3]</value>
      <webElementGuid>faed0b2d-141c-435e-abae-6c394930c1c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'yeardateOfBirth' and @id = 'yeardateOfBirth' and @placeholder = 'yyyy']</value>
      <webElementGuid>5020ed85-5817-4fe7-8a46-b46eab880cef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
