<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OngoingPrior Months Coverage_aidRequestSw</name>
   <tag></tag>
   <elementGuidId>1be7a399-0acf-434d-a6fe-b03f65279c74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='aidRequestSw']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#aidRequestSw</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aae57114-7cca-4981-aefe-df5025f1a725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>CHECKBOX</value>
      <webElementGuid>8f6def86-2bfb-441c-9b75-361859806923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aidRequestSw</value>
      <webElementGuid>454c38bf-710a-46b1-8d44-b28ff47d2d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>760973699::0</value>
      <webElementGuid>37db1f49-d7d5-4fb9-91ec-7de675e4e789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>4a91892e-1b5e-4788-839f-9377abbc710d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aidRequestSw</value>
      <webElementGuid>337604b6-4c09-447a-be9e-117c237adc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form35</value>
      <webElementGuid>077dc058-3b40-499f-921b-67d027c134d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>Aid</value>
      <webElementGuid>32b72492-fcfb-408c-9690-2f9f28ec4d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Aid</value>
      <webElementGuid>1febdf8a-8153-4710-8e77-a79d86181822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>aidRequestSw</value>
      <webElementGuid>edf53dd0-241f-456e-b42e-81ad7bf58904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setSubProgCd();enableOrDisableAr(0); enableDisableMedicaid(0);validateSubProgType();disablePriorMonthsOnEditMode('N');</value>
      <webElementGuid>c8e4c158-53ee-4240-bf7b-384ae6731d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aidRequestSw&quot;)</value>
      <webElementGuid>d0087426-6334-4b71-ad52-0520aede78c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>1b993e83-ef24-4276-8bfc-b2017cbe6313</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='aidRequestSw']</value>
      <webElementGuid>e18831eb-2da0-4b7e-a667-866e9c56b023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[15]/tbody/tr[2]/td/input</value>
      <webElementGuid>bd8aa2d5-ad29-4907-97cd-cf72295bd492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'CHECKBOX' and @name = 'aidRequestSw' and @id = 'aidRequestSw']</value>
      <webElementGuid>fbdb224d-22b6-42b1-bfe3-12988bf2148b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
