<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>c00bee6e-6cb2-430c-9e0d-5fcd9fe6f4a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='IMAGE'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0335f8ec-accc-4c85-ab9f-8045623d0db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>IMAGE</value>
      <webElementGuid>953972a7-3412-43b3-aae6-7eaa502b7249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>76</value>
      <webElementGuid>017c914a-e7ae-42ef-a2b6-099ca2851039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/tiers/images/buttonAddAll.gif</value>
      <webElementGuid>8dc9eefd-04de-424e-b8f9-ff6347408d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Click to Add All.</value>
      <webElementGuid>feb38e66-4daa-4322-824e-6a309973dd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b5d2e97b-91f9-4a5b-98a0-66720964e2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add All</value>
      <webElementGuid>a6578b18-b2fd-4636-8c7f-6ab676f87989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return doAddAll(document.form1.formNumber,document.form1.applicableForms)</value>
      <webElementGuid>ec59c241-55be-4bae-85fa-37599c812a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click to Add All.</value>
      <webElementGuid>07ea2c59-86f0-437c-9f91-67439e7b46e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[2]/tbody[1]/tr[2]/td[3]/table[@class=&quot;bodyFormLabels&quot;]/tbody[1]/tr[2]/td[2]/div[1]/table[1]/tbody[1]/tr[3]/td[1]/input[1]</value>
      <webElementGuid>e513ab13-c2ba-468a-9882-1babc50146c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>72cd0272-dfdf-4068-bc21-c7db8be62d22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='IMAGE'])[3]</value>
      <webElementGuid>ff13b746-17e5-4c76-96f4-f4f7a8ab11e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[3]/td/input</value>
      <webElementGuid>6e834354-f850-4889-ae1a-3fef3e437258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'IMAGE' and @src = '/tiers/images/buttonAddAll.gif' and @alt = 'Click to Add All.' and @title = 'Click to Add All.']</value>
      <webElementGuid>a8acf85e-ab75-4833-afc2-06e91e49d248</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
