<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_--_ssn3ssn</name>
   <tag></tag>
   <elementGuidId>6802d564-ec69-4b55-978f-f8c59995afde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ssn3ssn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ssn3ssn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9aaf4ad9-8b4c-4a36-a720-4981f8b8976e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6bc76bff-fae6-4a17-94a7-14a115ee1c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ssn3ssn</value>
      <webElementGuid>564e9bdf-13a9-4f53-ac7e-7ed966e7025a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ssn3ssn</value>
      <webElementGuid>d179e061-3e86-4836-9812-98e1055e6547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4ca27a63-6f4d-48ee-8cbe-8640b0cbe17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>10d594bd-5394-4c33-a17b-d3368728dbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>SSN</value>
      <webElementGuid>43a93f18-9423-4d54-9601-ad11f1dcea43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>SSN, four digit serial number</value>
      <webElementGuid>36ce9495-623a-44d6-8d00-10f291918708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>ssn</value>
      <webElementGuid>40adf890-2a3b-4e63-b9c0-90970bef0669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>310d57ce-4fcb-45e5-b3c8-6ba0dc4e3179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form35</value>
      <webElementGuid>4df205a3-7737-43c2-9fa6-ac712c8808c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>setSelectFlagFalse()</value>
      <webElementGuid>6e49b8cb-5e22-4da1-89fa-a1102984b267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ssaCheckbox('fromSSN');enableCreditSw(document.form1.scriptmode,document.form1.ssn1ssn,document.form1.ssn2ssn,document.form1.ssn3ssn,document.form1.reqDataBroker,document.form1.creditReportSw);ssaCheck(document.form1);</value>
      <webElementGuid>73ad9c9a-85cd-4679-bebb-1f1f13136ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value> joinFields(document.form1.ssn1ssn,document.form1.ssn2ssn,document.form1.ssn3ssn,document.form1.ssn,'N');  validateSSN(document.form1.ssn,document.form1.ssnMon,document.form1.ssnYear); isSSNChange();isSSNChangeVal() </value>
      <webElementGuid>ce6f3780-d60c-458a-9cbd-fc1258aaf040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ssn3ssn&quot;)</value>
      <webElementGuid>507f6900-2447-4069-814b-c65a0f781914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>7003b469-fd6c-48cb-89c9-77e0464c5921</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ssn3ssn']</value>
      <webElementGuid>3e24ad47-0ed3-41b3-9410-c6d21396a56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[6]</value>
      <webElementGuid>1414adea-cfb9-4102-852a-8061373eecb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ssn3ssn' and @id = 'ssn3ssn']</value>
      <webElementGuid>b8ac789e-f6a4-48de-a211-4d1df0841678</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
