<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Register Individual - Summary</name>
   <tag></tag>
   <elementGuidId>7ab8441a-094b-448b-af51-975541113906</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='FwTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FwTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>59338353-703c-485c-8d0f-9d9f66b9a0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FwTitle</value>
      <webElementGuid>fa41093e-e54b-4357-aee0-914f3fec6c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>TitleHiddenField</value>
      <webElementGuid>1b29587c-3e84-4a41-aecc-548b0cd3211b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>d3de7150-ffb1-421f-9b32-2af616c5812a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b057e6ae-bddd-454c-8ecf-394d828d8237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register Individual - Summary</value>
      <webElementGuid>7538e533-b7ac-408d-acef-d0c0e4e3dd02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FwTitle&quot;)</value>
      <webElementGuid>b71656d7-d87a-49e0-8cbc-ab76d068e721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>1a72d617-b819-4f1a-9f98-d34e1b58c7f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='FwTitle']</value>
      <webElementGuid>0bdb4675-c090-4954-8333-2d388dbd34e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='title']/label</value>
      <webElementGuid>da058115-81a8-471d-a3ef-3fbd3dcccc16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Household Individuals'])[1]/following::label[1]</value>
      <webElementGuid>3e7a1758-f4e3-4258-8bf2-262208db7379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T049991331'])[1]/preceding::label[1]</value>
      <webElementGuid>0d898355-277f-4fc7-9b4a-f41ce1fefa59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register Individual - Summary']/parent::*</value>
      <webElementGuid>35806efd-2176-45a7-ad9f-9010d09b0608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>d94cbe85-e5a3-4074-af8b-e463bf0c9411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'FwTitle' and (text() = 'Register Individual - Summary' or . = 'Register Individual - Summary')]</value>
      <webElementGuid>74ab386d-bc65-48d1-ac5c-8f666f190216</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
