<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Austin</name>
   <tag></tag>
   <elementGuidId>5e6b0a98-2f73-4a19-b14f-1fc199e57047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date'])[1]/following::li[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ac_even.ac_over</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b44f655c-3b6c-4e7c-8136-dd1888e7b9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac_even ac_over</value>
      <webElementGuid>c4a24ca5-af67-4bfb-bbc9-a94414bf8ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Austin</value>
      <webElementGuid>442840e7-703d-41d2-8fdc-fda4c76d4c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;ac_results&quot;]/ul[1]/li[@class=&quot;ac_even ac_over&quot;]</value>
      <webElementGuid>824aa5f8-7261-42fe-aa43-4f00ce1dd3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>98fe1331-d31b-407b-8b7e-e9c3b4591f5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date'])[1]/following::li[1]</value>
      <webElementGuid>056317c7-3798-48ac-9a62-9aaa8bb11c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Begin Date'])[1]/following::li[1]</value>
      <webElementGuid>dd70d135-4adf-4adb-8c88-ad7bc3f996f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='in']/parent::*</value>
      <webElementGuid>18d84090-3761-4bea-876c-49eeddcd470f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>ecd05dd6-9c19-4b94-915e-86829cc7bceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Austin' or . = 'Austin')]</value>
      <webElementGuid>43be23dd-5423-485a-adfd-fa660eb5d008</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
