<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NO YES_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>9e011d5b-018b-4780-b4c3-d9c42025dbaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='expeditedApplication']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#expeditedApplication</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>676751db-60f6-4c11-bf0f-001f1319938e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expeditedApplication</value>
      <webElementGuid>8911c6d9-858d-468c-9613-ad2da846fcba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Is this an expedited application</value>
      <webElementGuid>d6c1e9b0-a8e5-4f48-bec1-9fe121d89405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>e53795cc-f50e-474d-91ab-86ad50ae7a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expeditedApplication</value>
      <webElementGuid>51fecc72-205d-4756-aa95-d44972a54a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5d9583bb-af67-401f-9134-4948a536b03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form50</value>
      <webElementGuid>3e202663-811d-4d58-af86-dc80427b9367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>Is this an expedited application</value>
      <webElementGuid>b2645fed-debb-47f9-8aa5-30c68b191424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>expeditedApplication</value>
      <webElementGuid>00a458f6-8b9a-4794-a31f-ebd9faa94d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>validateExpediteQuestionForFS(this);</value>
      <webElementGuid>cd77821a-b67b-4c65-b710-d5d9f0a7a8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 
 NO
 YES
 </value>
      <webElementGuid>f62ffb01-a9ce-4746-86ee-f27fd19b9b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expeditedApplication&quot;)</value>
      <webElementGuid>b695e69d-f97f-4bc9-aa8f-0d0435041a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>2ffc7fc8-b5fb-49df-a6db-7cdb5e522e4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='expeditedApplication']</value>
      <webElementGuid>5d8bafd7-fae2-4b55-b9e8-e2cb680ef2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is this an expedited application?'])[1]/following::select[1]</value>
      <webElementGuid>7116b4cd-24a4-4358-9167-0140ce6ffcf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appointment Mode:'])[1]/following::select[2]</value>
      <webElementGuid>e1cd3c72-bfd1-486d-bd56-026445f7140f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is this application registration being performed for an Outstationed Facility?'])[1]/preceding::select[1]</value>
      <webElementGuid>4c56eee1-2c6b-430f-a886-fd1298f15bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program List'])[1]/preceding::select[2]</value>
      <webElementGuid>0b467c84-1039-4a4f-8890-16478c47b2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/select</value>
      <webElementGuid>fede99f1-491c-4160-829f-18b0281f9e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'expeditedApplication' and @id = 'expeditedApplication' and (text() = '
 
 NO
 YES
 ' or . = '
 
 NO
 YES
 ')]</value>
      <webElementGuid>20f7cda9-c26c-42ec-97b6-239492c74ae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
