<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NO YES_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>888035d2-6aa1-4836-a36b-d49e59631c29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='apptYesorNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#apptYesorNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>15009c0a-62d5-4fd9-be39-ae3ad333a745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>scheduleAnAppointment</value>
      <webElementGuid>186d312c-f4f2-4e56-b1c9-272312544b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Is an appointment required or requested to process this application ?</value>
      <webElementGuid>d635ffb0-c9c3-4d5e-b912-ceb2e18fd8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>f77c5834-04c6-4588-a7ff-b3e5bd4d6ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apptYesorNo</value>
      <webElementGuid>8421fa9d-3d61-4390-8f5a-f9deba2b6d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>884383fe-209e-47c9-932c-7b2fb907d622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form50</value>
      <webElementGuid>28a8a830-deae-4fbf-98ce-d27fdcbe3300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>Is an appointment required or requested to process this application ?</value>
      <webElementGuid>a5ade443-1819-4518-94fc-1a0499c3a055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>scheduleAnAppointment</value>
      <webElementGuid>5abc2318-3588-4b19-b183-c1488e00cd2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>disableFieldsOnYes(document.form1.scheduleAnAppointment,document.form1.performTanfRedirect,document.form1.addToStandByList);enabledFlexApptQuestion();if(document.form1.tanfVal.value == '2') {document.form1.performTanfRedirect.disabled = true;}</value>
      <webElementGuid>fa0bbe27-d834-4574-81e9-59ad4f065bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 NO
 YES
 </value>
      <webElementGuid>23d3e613-9390-495d-acea-c07d23c6da41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apptYesorNo&quot;)</value>
      <webElementGuid>c7c8fa1f-948e-4740-8c81-7f20e532843d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>93e92ef7-39a8-41d8-adf1-4a001dbb6e60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='apptYesorNo']</value>
      <webElementGuid>3239b911-952c-4585-b9ad-b66c38f68dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is an appointment required or requested to process this application ?'])[1]/following::select[1]</value>
      <webElementGuid>1c687476-5ea5-450b-acf0-4af881c4bee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appointment Required or Requested'])[1]/following::select[1]</value>
      <webElementGuid>9dc27a48-798d-444c-ae41-9711fd3aa519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you conducting a flexible appointment interview now?'])[1]/preceding::select[1]</value>
      <webElementGuid>24e672ba-2510-4eb9-86e1-f7f4ee117160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Was SNAP Requested??'])[1]/preceding::select[2]</value>
      <webElementGuid>9b50d107-8fa7-451d-bcea-58540de7dee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[17]/tbody/tr/td[2]/select</value>
      <webElementGuid>13237e65-53ab-4da4-960c-5cb58ed77039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'scheduleAnAppointment' and @id = 'apptYesorNo' and (text() = '
 NO
 YES
 ' or . = '
 NO
 YES
 ')]</value>
      <webElementGuid>3a353d1c-0ed7-4c36-9405-be8070755361</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
