<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NO YES_1_2</name>
   <tag></tag>
   <elementGuidId>9014e7b8-8c24-4ae8-bd48-2d98d50259ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='viewAssociatedCases']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#viewAssociatedCases</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2d6667d7-7e44-4e9e-a467-ae2188acac98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>viewAssociatedCases</value>
      <webElementGuid>29926b82-876d-46e1-8b00-273306eee641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Do you wish to view associated cases?</value>
      <webElementGuid>425b5a5f-00a5-410c-bc46-488c877d7c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9e445d1b-dd73-489f-ab13-fbbf55be2389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>viewAssociatedCases</value>
      <webElementGuid>5dedf373-ea13-43a0-9a31-d1779154bb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bd68c028-1d4c-48d2-95b7-c36d6e709422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formStyle</value>
      <webElementGuid>49b3ca01-638f-48a4-83a5-6eca2e275d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>Do you wish to view associated cases?</value>
      <webElementGuid>98dabd7e-2502-4b73-a233-8b8b814aaeec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>viewAssociatedCases</value>
      <webElementGuid>0663b3f7-06ab-46c5-9d40-1d14d7d837c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 NO
 YES
 </value>
      <webElementGuid>0db75119-58ca-4357-80c2-a037b8239a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewAssociatedCases&quot;)</value>
      <webElementGuid>d82ed3b8-3f20-43bc-9ccb-8d8668e0fd88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>f0dd0c1e-190b-4ac4-9642-144f6ad88976</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='viewAssociatedCases']</value>
      <webElementGuid>c439054c-e444-4aea-ad9e-0418a7f73e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you wish to view associated cases?'])[1]/following::select[1]</value>
      <webElementGuid>cf72d860-878d-4c8c-88c4-28955c510a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TIERS'])[1]/following::select[1]</value>
      <webElementGuid>5781557a-3f83-41aa-bbd9-c8af61bc9882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/html[1]/body[1]/form[1]/table[2]/tbody[1]/tr[2]/td[3]/table[15]/tbody[1]/tr[1]/td[1]/div[1]'])[1]/preceding::select[2]</value>
      <webElementGuid>a45b4a38-b543-49ee-aa77-81d79321de93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>9712674f-7ca3-4f80-b11c-b02004196f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'viewAssociatedCases' and @id = 'viewAssociatedCases' and (text() = '
 NO
 YES
 ' or . = '
 NO
 YES
 ')]</value>
      <webElementGuid>51a8fdaf-c547-4893-a619-250347ad2663</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
