<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NO YES_1_2_3</name>
   <tag></tag>
   <elementGuidId>e0b54240-6a5d-4228-9093-9d77476252f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='establishNewIndividual']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#establishNewIndividual</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a82f52ae-0c93-4211-9cd2-3744030b4177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>establishNewIndividual</value>
      <webElementGuid>3bfefcbd-4a3c-4adb-bb61-7dc2a751ced6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Do you wish to establish as a new individual?</value>
      <webElementGuid>7d5dd8fd-ab10-4c99-9c36-13dab221f47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a2799de1-6bd0-4780-8e86-961723df658c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>establishNewIndividual</value>
      <webElementGuid>c9d2a270-3d16-4cd0-8aee-519513bb0352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7c9b0352-7d14-4529-906f-46ec1ce0756b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formStyle</value>
      <webElementGuid>a64d7349-d524-4cb8-97a0-f884d72a7bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>Do you wish to establish as a new individual?</value>
      <webElementGuid>12995015-82fa-4d5a-9e9a-d868e6c4f88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>establishNewIndividual</value>
      <webElementGuid>8a20ca41-0cb6-492f-bd0b-56d2ac2384b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 NO
 YES
 </value>
      <webElementGuid>d1029d35-c5ee-4ffb-a029-3aa66a8dc6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;establishNewIndividual&quot;)</value>
      <webElementGuid>d8ab2d9a-c610-4c69-b0a2-70ce2b6fe23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>2bf9c37c-3c88-4c68-a2fc-9b79952b8798</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='establishNewIndividual']</value>
      <webElementGuid>911811c5-453e-49b4-94d1-fe5ee47b3cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you wish to view associated cases?'])[1]/following::select[2]</value>
      <webElementGuid>f157b2e0-3c00-4946-9502-e1f31d30ed45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'button2', '&quot;', ')')])[1]/preceding::select[1]</value>
      <webElementGuid>0977de92-6705-4d60-9e10-cea44026d859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/select</value>
      <webElementGuid>335eab0b-dd31-48ab-8a02-4e2ed99f1354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'establishNewIndividual' and @id = 'establishNewIndividual' and (text() = '
 NO
 YES
 ' or . = '
 NO
 YES
 ')]</value>
      <webElementGuid>8692a149-3b41-4aa3-ae80-1cbee90ef843</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
