<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AndersonAndrewsAngelinaAransasArcher_1d5592</name>
   <tag></tag>
   <elementGuidId>1e7c5a13-4cff-40d6-8e0b-ed62898f9dde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='county']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#county</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aa0713f0-02e1-49ce-b07b-5cc8785c66fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>county</value>
      <webElementGuid>c2ad4605-6fac-4797-b57e-897b07e99aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>county</value>
      <webElementGuid>f91a6d1d-1d6c-4869-aeb9-2429bbdcf413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>County</value>
      <webElementGuid>0dca8b48-53dd-41e0-8ead-7aacb0449b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b03528a1-7dd9-4aec-8049-040303f348d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>County</value>
      <webElementGuid>7f5b4aa4-3d60-4fc3-a473-da00c1eddafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>addressGroup</value>
      <webElementGuid>0396c607-be4a-4d2a-9eca-2dac67fac267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form100</value>
      <webElementGuid>a484113e-219c-44ac-ace8-85817c4e63a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>isDisasterCounty();</value>
      <webElementGuid>6bd40494-0ce6-4776-9aad-01ab57911d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>isComplete(form2.county);</value>
      <webElementGuid>873d2b8f-612f-40ee-98ac-992ff16688b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b268db17-f54e-44bc-b96e-0ccd75993fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	Anderson
	Andrews
	Angelina
	Aransas
	Archer
	Armstrong
	Atascosa
	Austin
	Bailey
	Bandera
	Bastrop
	Baylor
	Bee
	Bell
	Bexar
	Blanco
	Borden
	Bosque
	Bowie
	Brazoria
	Brazos
	Brewster
	Briscoe
	Brooks
	Brown
	Burleson
	Burnet
	Caldwell
	Calhoun
	Callahan
	Cameron
	Camp
	Carson
	Cass
	Castro
	Chambers
	Cherokee
	Childress
	Clay
	Cochran
	Coke
	Coleman
	Collin
	Collingsworth
	Colorado
	Comal
	Comanche
	Concho
	Cooke
	Coryell
	Cottle
	Crane
	Crockett
	Crosby
	Culberson
	Dallam
	Dallas
	Dawson
	Deaf Smith
	Delta
	Denton
	De Witt
	Dickens
	Dimmit
	Donley
	Duval
	Eastland
	Ector
	Edwards
	Ellis
	El Paso
	Erath
	Falls
	Fannin
	Fayette
	Fisher
	Floyd
	Foard
	Fort Bend
	Franklin
	Freestone
	Frio
	Gaines
	Galveston
	Garza
	Gillespie
	Glasscock
	Goliad
	Gonzales
	Gray
	Grayson
	Gregg
	Grimes
	Guadalupe
	Hale
	Hall
	Hamilton
	Hansford
	Hardeman
	Hardin
	Harris
	Harrison
	Hartley
	Haskell
	Hays
	Hemphill
	Henderson
	Hidalgo
	Hill
	Hockley
	Hood
	Hopkins
	Houston
	Howard
	Hudspeth
	Hunt
	Hutchinson
	Irion
	Jack
	Jackson
	Jasper
	Jeff Davis
	Jefferson
	Jim Hogg
	Jim Wells
	Johnson
	Jones
	Karnes
	Kaufman
	Kendall
	Kenedy
	Kent
	Kerr
	Kimble
	King
	Kinney
	Kleberg
	Knox
	Lamar
	Lamb
	Lampasas
	La Salle
	Lavaca
	Lee
	Leon
	Liberty
	Limestone
	Lipscomb
	Live Oak
	Llano
	Loving
	Lubbock
	Lynn
	Madison
	Marion
	Martin
	Mason
	Matagorda
	Maverick
	McCulloch
	McLennan
	McMullen
	Medina
	Menard
	Midland
	Milam
	Mills
	Mitchell
	Montague
	Montgomery
	Moore
	Morris
	Motley
	Nacogdoches
	Navarro
	Newton
	Nolan
	Nueces
	Ochiltree
	Oldham
	Orange
	Palo Pinto
	Panola
	Parker
	Parmer
	Pecos
	Polk
	Potter
	Presidio
	Rains
	Randall
	Reagan
	Real
	Red River
	Reeves
	Refugio
	Roberts
	Robertson
	Rockwall
	Runnels
	Rusk
	Sabine
	San Augustine
	San Jacinto
	San Patricio
	San Saba
	Schleicher
	Scurry
	Shackelford
	Shelby
	Sherman
	Smith
	Somervell
	Starr
	Stephens
	Sterling
	Stonewall
	Sutton
	Swisher
	Tarrant
	Taylor
	Terrell
	Terry
	Throckmorton
	Titus
	Tom Green
	Travis
	Trinity
	Tyler
	Upshur
	Upton
	Uvalde
	Val Verde
	Van Zandt
	Victoria
	Walker
	Waller
	Ward
	Washington
	Webb
	Wharton
	Wheeler
	Wichita
	Wilbarger
	Willacy
	Williamson
	Wilson
	Winkler
	Wise
	Wood
	Yoakum
	Young
	Zapata
	Zavala
	Not a Texas County
	</value>
      <webElementGuid>09d5a46b-7b0b-4122-a613-394e72fec7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;county&quot;)</value>
      <webElementGuid>0edfcc98-d8f7-4404-9982-b14b39c6ec90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>d7f9d637-c5d2-4c05-b3cf-7ee60df0202a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='county']</value>
      <webElementGuid>080aef52-6e46-4841-95fb-ed84f3d8973a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='County:'])[1]/following::select[1]</value>
      <webElementGuid>de209828-ec0f-4c13-9be3-74939609897a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Line 2:'])[1]/following::select[1]</value>
      <webElementGuid>322c1b78-9222-4fda-bf25-fff5430de3ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City:'])[1]/preceding::select[1]</value>
      <webElementGuid>ce18ae58-8be1-4170-bec9-51239e95a30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State:'])[1]/preceding::select[1]</value>
      <webElementGuid>3182a506-da26-4f99-b869-19dba3184250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/select</value>
      <webElementGuid>1b54a49a-0cf4-43be-b28e-ca63b6f00c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'county' and @id = 'county' and (text() = '
	Anderson
	Andrews
	Angelina
	Aransas
	Archer
	Armstrong
	Atascosa
	Austin
	Bailey
	Bandera
	Bastrop
	Baylor
	Bee
	Bell
	Bexar
	Blanco
	Borden
	Bosque
	Bowie
	Brazoria
	Brazos
	Brewster
	Briscoe
	Brooks
	Brown
	Burleson
	Burnet
	Caldwell
	Calhoun
	Callahan
	Cameron
	Camp
	Carson
	Cass
	Castro
	Chambers
	Cherokee
	Childress
	Clay
	Cochran
	Coke
	Coleman
	Collin
	Collingsworth
	Colorado
	Comal
	Comanche
	Concho
	Cooke
	Coryell
	Cottle
	Crane
	Crockett
	Crosby
	Culberson
	Dallam
	Dallas
	Dawson
	Deaf Smith
	Delta
	Denton
	De Witt
	Dickens
	Dimmit
	Donley
	Duval
	Eastland
	Ector
	Edwards
	Ellis
	El Paso
	Erath
	Falls
	Fannin
	Fayette
	Fisher
	Floyd
	Foard
	Fort Bend
	Franklin
	Freestone
	Frio
	Gaines
	Galveston
	Garza
	Gillespie
	Glasscock
	Goliad
	Gonzales
	Gray
	Grayson
	Gregg
	Grimes
	Guadalupe
	Hale
	Hall
	Hamilton
	Hansford
	Hardeman
	Hardin
	Harris
	Harrison
	Hartley
	Haskell
	Hays
	Hemphill
	Henderson
	Hidalgo
	Hill
	Hockley
	Hood
	Hopkins
	Houston
	Howard
	Hudspeth
	Hunt
	Hutchinson
	Irion
	Jack
	Jackson
	Jasper
	Jeff Davis
	Jefferson
	Jim Hogg
	Jim Wells
	Johnson
	Jones
	Karnes
	Kaufman
	Kendall
	Kenedy
	Kent
	Kerr
	Kimble
	King
	Kinney
	Kleberg
	Knox
	Lamar
	Lamb
	Lampasas
	La Salle
	Lavaca
	Lee
	Leon
	Liberty
	Limestone
	Lipscomb
	Live Oak
	Llano
	Loving
	Lubbock
	Lynn
	Madison
	Marion
	Martin
	Mason
	Matagorda
	Maverick
	McCulloch
	McLennan
	McMullen
	Medina
	Menard
	Midland
	Milam
	Mills
	Mitchell
	Montague
	Montgomery
	Moore
	Morris
	Motley
	Nacogdoches
	Navarro
	Newton
	Nolan
	Nueces
	Ochiltree
	Oldham
	Orange
	Palo Pinto
	Panola
	Parker
	Parmer
	Pecos
	Polk
	Potter
	Presidio
	Rains
	Randall
	Reagan
	Real
	Red River
	Reeves
	Refugio
	Roberts
	Robertson
	Rockwall
	Runnels
	Rusk
	Sabine
	San Augustine
	San Jacinto
	San Patricio
	San Saba
	Schleicher
	Scurry
	Shackelford
	Shelby
	Sherman
	Smith
	Somervell
	Starr
	Stephens
	Sterling
	Stonewall
	Sutton
	Swisher
	Tarrant
	Taylor
	Terrell
	Terry
	Throckmorton
	Titus
	Tom Green
	Travis
	Trinity
	Tyler
	Upshur
	Upton
	Uvalde
	Val Verde
	Van Zandt
	Victoria
	Walker
	Waller
	Ward
	Washington
	Webb
	Wharton
	Wheeler
	Wichita
	Wilbarger
	Willacy
	Williamson
	Wilson
	Winkler
	Wise
	Wood
	Yoakum
	Young
	Zapata
	Zavala
	Not a Texas County
	' or . = '
	Anderson
	Andrews
	Angelina
	Aransas
	Archer
	Armstrong
	Atascosa
	Austin
	Bailey
	Bandera
	Bastrop
	Baylor
	Bee
	Bell
	Bexar
	Blanco
	Borden
	Bosque
	Bowie
	Brazoria
	Brazos
	Brewster
	Briscoe
	Brooks
	Brown
	Burleson
	Burnet
	Caldwell
	Calhoun
	Callahan
	Cameron
	Camp
	Carson
	Cass
	Castro
	Chambers
	Cherokee
	Childress
	Clay
	Cochran
	Coke
	Coleman
	Collin
	Collingsworth
	Colorado
	Comal
	Comanche
	Concho
	Cooke
	Coryell
	Cottle
	Crane
	Crockett
	Crosby
	Culberson
	Dallam
	Dallas
	Dawson
	Deaf Smith
	Delta
	Denton
	De Witt
	Dickens
	Dimmit
	Donley
	Duval
	Eastland
	Ector
	Edwards
	Ellis
	El Paso
	Erath
	Falls
	Fannin
	Fayette
	Fisher
	Floyd
	Foard
	Fort Bend
	Franklin
	Freestone
	Frio
	Gaines
	Galveston
	Garza
	Gillespie
	Glasscock
	Goliad
	Gonzales
	Gray
	Grayson
	Gregg
	Grimes
	Guadalupe
	Hale
	Hall
	Hamilton
	Hansford
	Hardeman
	Hardin
	Harris
	Harrison
	Hartley
	Haskell
	Hays
	Hemphill
	Henderson
	Hidalgo
	Hill
	Hockley
	Hood
	Hopkins
	Houston
	Howard
	Hudspeth
	Hunt
	Hutchinson
	Irion
	Jack
	Jackson
	Jasper
	Jeff Davis
	Jefferson
	Jim Hogg
	Jim Wells
	Johnson
	Jones
	Karnes
	Kaufman
	Kendall
	Kenedy
	Kent
	Kerr
	Kimble
	King
	Kinney
	Kleberg
	Knox
	Lamar
	Lamb
	Lampasas
	La Salle
	Lavaca
	Lee
	Leon
	Liberty
	Limestone
	Lipscomb
	Live Oak
	Llano
	Loving
	Lubbock
	Lynn
	Madison
	Marion
	Martin
	Mason
	Matagorda
	Maverick
	McCulloch
	McLennan
	McMullen
	Medina
	Menard
	Midland
	Milam
	Mills
	Mitchell
	Montague
	Montgomery
	Moore
	Morris
	Motley
	Nacogdoches
	Navarro
	Newton
	Nolan
	Nueces
	Ochiltree
	Oldham
	Orange
	Palo Pinto
	Panola
	Parker
	Parmer
	Pecos
	Polk
	Potter
	Presidio
	Rains
	Randall
	Reagan
	Real
	Red River
	Reeves
	Refugio
	Roberts
	Robertson
	Rockwall
	Runnels
	Rusk
	Sabine
	San Augustine
	San Jacinto
	San Patricio
	San Saba
	Schleicher
	Scurry
	Shackelford
	Shelby
	Sherman
	Smith
	Somervell
	Starr
	Stephens
	Sterling
	Stonewall
	Sutton
	Swisher
	Tarrant
	Taylor
	Terrell
	Terry
	Throckmorton
	Titus
	Tom Green
	Travis
	Trinity
	Tyler
	Upshur
	Upton
	Uvalde
	Val Verde
	Van Zandt
	Victoria
	Walker
	Waller
	Ward
	Washington
	Webb
	Wharton
	Wheeler
	Wichita
	Wilbarger
	Willacy
	Williamson
	Wilson
	Winkler
	Wise
	Wood
	Yoakum
	Young
	Zapata
	Zavala
	Not a Texas County
	')]</value>
      <webElementGuid>c1521241-c198-4943-ae24-575fe068d13c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
