<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NO YES_1</name>
   <tag></tag>
   <elementGuidId>1baa8e3a-ef94-468d-977a-17b222413acc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='applicationAidSw']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#applicationAidSw</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7d9bfafa-e810-4396-aaf5-23e006422e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>applicationAidSw</value>
      <webElementGuid>35fc615f-6b17-43ff-9095-23fad6e7e48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Is this an Application for Aid?</value>
      <webElementGuid>e8d5cd92-d00b-43fd-81aa-2946c0693220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>b6dcb45f-51a2-43bd-ab8f-57b0c47bb6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>applicationAidSw</value>
      <webElementGuid>6d2f8c10-f55f-4298-af8c-a076faa89626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d1a2dbad-f54f-4d26-bfa1-ac76c3610983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form50</value>
      <webElementGuid>bd850924-6376-4643-8614-46489f399e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>Is this an Application for Aid?</value>
      <webElementGuid>2cbb7485-4910-470e-8516-7f6c204c9fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>applicationAidSw</value>
      <webElementGuid>8c0f6f7c-7218-4e91-8943-8a376e5fc0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>validateType(new Array('applicationAidSw','spraSw'))</value>
      <webElementGuid>bfae9cc4-b7b4-4bbd-ae5d-5a3d1d198ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 NO
 YES
 </value>
      <webElementGuid>b6090e42-94d8-45ca-acb1-8c9e24276a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;applicationAidSw&quot;)</value>
      <webElementGuid>532aadfd-ce14-4249-adde-eb91449489f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>c7b23854-c41c-4895-924f-ce481516fcb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='applicationAidSw']</value>
      <webElementGuid>61b6b97e-b626-4386-a807-540be62d5990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is this an Application for Aid?'])[1]/following::select[1]</value>
      <webElementGuid>aeefc102-457b-438c-8f1c-ec80b4bfca95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is this a PASARR?'])[1]/following::select[2]</value>
      <webElementGuid>8918ba37-e68f-4919-af35-1786f3aa7998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is this an SPRA?'])[1]/preceding::select[1]</value>
      <webElementGuid>4e97d11d-4899-4ca7-9fdb-5649373710c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is this a request for Hospice?'])[1]/preceding::select[2]</value>
      <webElementGuid>39e7edc9-17e9-4b6a-b058-4e773d48dcfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/select</value>
      <webElementGuid>6ae9f0de-1999-4009-8013-c1a2cf6c123a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'applicationAidSw' and @id = 'applicationAidSw' and (text() = '
 NO
 YES
 ' or . = '
 NO
 YES
 ')]</value>
      <webElementGuid>9b6fd5da-8bf1-4418-a707-e692c1fa08c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
