<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Hispanic Non-Hispanic Not Provided</name>
   <tag></tag>
   <elementGuidId>55591f00-7203-4b14-aff5-98be9ad77bc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ethnicity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ethnicity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3be4dcf5-02da-4c9c-ad23-57a08298fb2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ethnicity</value>
      <webElementGuid>fdffde8f-fc73-461a-997d-01202fe77892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Ethnicity</value>
      <webElementGuid>f6349ce3-8d51-4943-8895-3e1ceb3546ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>20374fff-59a7-41c9-bc37-1c5ccca38595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ethnicity</value>
      <webElementGuid>0561c0d0-4c30-45b8-a6e9-7fbe221f4099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0c670e9c-2c31-4d32-914f-973b65602c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form100</value>
      <webElementGuid>0cd72a2c-049c-44dc-820e-c28fc41836e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>Ethnicity</value>
      <webElementGuid>26a7a8e1-df54-4455-a075-1fd8e2c66cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>ethnicity</value>
      <webElementGuid>03e7c550-90e6-4650-8d3c-0f7ced949814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 
 Hispanic
 Non-Hispanic
 Not Provided
 </value>
      <webElementGuid>df4c4b92-cff4-4757-97c0-45cbfa405b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ethnicity&quot;)</value>
      <webElementGuid>5861eede-89aa-43a4-876f-c53bff93b934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>4f2e65ba-82f4-4e08-9a44-58c971c8e966</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ethnicity']</value>
      <webElementGuid>d506a3e5-88e2-4316-984b-4022a803ad4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ethnicity:'])[1]/following::select[1]</value>
      <webElementGuid>2121728d-15eb-4973-9a15-5e2421070153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Race:'])[1]/preceding::select[1]</value>
      <webElementGuid>4e2ebaff-aea4-4683-a6d4-18a255f098f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHIP Client Id:'])[1]/preceding::select[2]</value>
      <webElementGuid>11388385-6966-4e2a-90f7-83548d2fc8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[16]/tbody/tr/td[2]/select</value>
      <webElementGuid>7e6bc295-1382-40ea-a8ff-dd3565c82634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ethnicity' and @id = 'ethnicity' and (text() = '
 
 Hispanic
 Non-Hispanic
 Not Provided
 ' or . = '
 
 Hispanic
 Non-Hispanic
 Not Provided
 ')]</value>
      <webElementGuid>47cf915b-a1e4-483b-a4ea-22bc4fe1b945</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
