<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ENNENWSSESWW</name>
   <tag></tag>
   <elementGuidId>fa5f5e32-6462-4171-acc3-e852d403e2d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='direction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#direction</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f093592d-bba0-4e05-8a8f-8b4546310409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>direction</value>
      <webElementGuid>b1cbad60-e8ab-4161-9f67-69da4c726d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>direction</value>
      <webElementGuid>2d04e527-7b7a-4922-b00f-9844898ff188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Direction</value>
      <webElementGuid>5796aafb-ac50-4664-9686-4629e299845b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>aeb5a203-24a2-486a-8296-e545a6b9ea18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>Dir.</value>
      <webElementGuid>9e0d16b6-f874-4823-bae0-5c2ed1220f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>addressGroup</value>
      <webElementGuid>c2749bc7-fbc4-4727-b9fc-3c4ab2b83157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form50</value>
      <webElementGuid>c0f7a012-895c-4760-8f97-8a6d9b044a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	E
	N
	NE
	NW
	S
	SE
	SW
	W
	</value>
      <webElementGuid>5d85adc5-4ad3-4872-93e3-8a7c05d27309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;direction&quot;)</value>
      <webElementGuid>56c9290e-b44e-4507-9bc5-7260df5ae3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>249b5b86-392b-4c56-950e-751c2daa7432</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='direction']</value>
      <webElementGuid>3b439cd7-f3d7-4af7-97e8-164a17add83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dir.:'])[1]/following::select[1]</value>
      <webElementGuid>a0435b81-a39e-48c3-8925-098ba7bc44dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fraction:'])[1]/following::select[1]</value>
      <webElementGuid>4c594dc3-bf17-4915-8512-1bafa86dd3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Str. Name/Rural Addr:'])[1]/preceding::select[1]</value>
      <webElementGuid>3a2e6471-d59b-4748-942d-c6acfba3f9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Str. Type:'])[1]/preceding::select[1]</value>
      <webElementGuid>f2217bb0-8a73-4769-96ba-a3bc78cc47cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/select</value>
      <webElementGuid>73caecd0-e2b1-4088-afb4-156fdf66408e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'direction' and @id = 'direction' and (text() = '
	E
	N
	NE
	NW
	S
	SE
	SW
	W
	' or . = '
	E
	N
	NE
	NW
	S
	SE
	SW
	W
	')]</value>
      <webElementGuid>d5afa148-7699-441f-aed5-d772d6f865ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
