<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AlleyAnnexArcadeAvenueBayouBeachBend_e55eba</name>
   <tag></tag>
   <elementGuidId>07853126-268c-4066-ac96-683cf050885c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='strType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#strType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c8781703-6dc7-415f-92fc-63a1b0cd9e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>strType</value>
      <webElementGuid>d7309aa6-617d-4263-b14b-ccbf6ce959e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>strType</value>
      <webElementGuid>32f38454-2eec-4093-bca4-a8f44fafbb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Street Type</value>
      <webElementGuid>1e6823bf-e02e-4345-b78e-ce2de3e1fea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c3fa9d61-f1ce-45ab-a385-a1f6bb5fe5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>Str. Type</value>
      <webElementGuid>cb804d97-805a-4831-86e9-3e016d4709e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>addressGroup</value>
      <webElementGuid>1cf8cd7d-5f80-4740-892d-7c9e7906e872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form100</value>
      <webElementGuid>771146c9-431e-45e2-8100-f0a5acdfce70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	Alley
	Annex
	Arcade
	Avenue
	Bayou
	Beach
	Bend
	Bluff
	Bluffs
	Bottom
	Boulevard
	Branch
	Bridge
	Brook
	Brooks
	Burg
	Burgs
	Bypass
	Camp
	Canyon
	Cape
	Causeway
	Center
	Centers
	Circle
	Circles
	Cliff
	Cliffs
	Club
	Common
	Corner
	Corners
	Course
	Court
	Courts
	Cove
	Coves
	Creek
	Crescent
	Crest
	Crossing
	Crossroad
	Curve
	Dale
	Dam
	Divide
	Drive
	Drives
	Estate
	Estates
	Expressway
	Extension
	Extensions
	Fall
	Falls
	Ferry
	Field
	Fields
	Flat
	Flats
	Ford
	Fords
	Forest
	Forge
	Forges
	Fork
	Forks
	Fort
	Freeway
	Garden
	Gardens
	Gateway
	Glen
	Glens
	Green
	Greens
	Grov
	Grove
	Harbor
	Harbors
	Haven
	Heights
	Highway
	Hill
	Hills
	Hollow
	Inlet
	Island
	Islands
	Isle
	Junction
	Junctions
	Key
	Keys
	Knoll
	Knolls
	Lake
	Lakes
	Land
	Landing
	Lane
	Light
	Lights
	Loaf
	Lock
	Locks
	Lodge
	Loop
	Mall
	Manor
	Manors
	Meadow
	Meadows
	Mews
	Mill
	Mills
	Mission
	Motorway
	Mount
	Mountain
	Mountains
	Neck
	Orchard
	Oval
	Overpass
	Park
	Parkway
	Pass
	Passage
	Path
	Pike
	Pine
	Pines
	Place
	Plain
	Plains
	Plaza
	Point
	Points
	Port
	Ports
	Prairie
	Radial
	Ramp
	Ranch
	Rapid
	Rapids
	Rest
	Ridge
	Ridges
	River
	Road
	Roads
	Route
	Row
	Rue
	Run
	Shoal
	Shoals
	Shore
	Shores
	Skyway
	Spring
	Springs
	Spur
	Square
	Squares
	Station
	Stravenue
	Stream
	Street
	Streets
	Summit
	Terrace
	Throughway
	Trace
	Track
	Trafficway
	Trail
	Tunnel
	Turnpike
	Underpass
	Union
	Unions
	Valley
	Valleys
	Viaduct
	View
	Views
	Village
	Villages
	Ville
	Vista
	Walk
	Wall
	Way
	Ways
	Well
	Wells
	</value>
      <webElementGuid>b3dde195-1ea0-4496-89df-cfedea2406ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;strType&quot;)</value>
      <webElementGuid>4f2a029c-3f3c-4a12-afd5-a2e793593e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>cd5ef1fe-fa34-47f7-b21c-1aea0d215941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='strType']</value>
      <webElementGuid>34c9a64a-6cf6-4edb-bcae-037dc3cc7f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Str. Type:'])[1]/following::select[1]</value>
      <webElementGuid>aec9a470-617d-4257-b9bf-d41371ea8c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Str. Name/Rural Addr:'])[1]/following::select[1]</value>
      <webElementGuid>7b067b24-e520-43eb-ac4e-7c1861fa70b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dwelling Type:'])[1]/preceding::select[1]</value>
      <webElementGuid>1f8b65ec-7dad-4e5e-aa99-f424e7a4e49f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/select</value>
      <webElementGuid>a1056897-1349-4124-9bf3-414fc334ea3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'strType' and @id = 'strType' and (text() = '
	Alley
	Annex
	Arcade
	Avenue
	Bayou
	Beach
	Bend
	Bluff
	Bluffs
	Bottom
	Boulevard
	Branch
	Bridge
	Brook
	Brooks
	Burg
	Burgs
	Bypass
	Camp
	Canyon
	Cape
	Causeway
	Center
	Centers
	Circle
	Circles
	Cliff
	Cliffs
	Club
	Common
	Corner
	Corners
	Course
	Court
	Courts
	Cove
	Coves
	Creek
	Crescent
	Crest
	Crossing
	Crossroad
	Curve
	Dale
	Dam
	Divide
	Drive
	Drives
	Estate
	Estates
	Expressway
	Extension
	Extensions
	Fall
	Falls
	Ferry
	Field
	Fields
	Flat
	Flats
	Ford
	Fords
	Forest
	Forge
	Forges
	Fork
	Forks
	Fort
	Freeway
	Garden
	Gardens
	Gateway
	Glen
	Glens
	Green
	Greens
	Grov
	Grove
	Harbor
	Harbors
	Haven
	Heights
	Highway
	Hill
	Hills
	Hollow
	Inlet
	Island
	Islands
	Isle
	Junction
	Junctions
	Key
	Keys
	Knoll
	Knolls
	Lake
	Lakes
	Land
	Landing
	Lane
	Light
	Lights
	Loaf
	Lock
	Locks
	Lodge
	Loop
	Mall
	Manor
	Manors
	Meadow
	Meadows
	Mews
	Mill
	Mills
	Mission
	Motorway
	Mount
	Mountain
	Mountains
	Neck
	Orchard
	Oval
	Overpass
	Park
	Parkway
	Pass
	Passage
	Path
	Pike
	Pine
	Pines
	Place
	Plain
	Plains
	Plaza
	Point
	Points
	Port
	Ports
	Prairie
	Radial
	Ramp
	Ranch
	Rapid
	Rapids
	Rest
	Ridge
	Ridges
	River
	Road
	Roads
	Route
	Row
	Rue
	Run
	Shoal
	Shoals
	Shore
	Shores
	Skyway
	Spring
	Springs
	Spur
	Square
	Squares
	Station
	Stravenue
	Stream
	Street
	Streets
	Summit
	Terrace
	Throughway
	Trace
	Track
	Trafficway
	Trail
	Tunnel
	Turnpike
	Underpass
	Union
	Unions
	Valley
	Valleys
	Viaduct
	View
	Views
	Village
	Villages
	Ville
	Vista
	Walk
	Wall
	Way
	Ways
	Well
	Wells
	' or . = '
	Alley
	Annex
	Arcade
	Avenue
	Bayou
	Beach
	Bend
	Bluff
	Bluffs
	Bottom
	Boulevard
	Branch
	Bridge
	Brook
	Brooks
	Burg
	Burgs
	Bypass
	Camp
	Canyon
	Cape
	Causeway
	Center
	Centers
	Circle
	Circles
	Cliff
	Cliffs
	Club
	Common
	Corner
	Corners
	Course
	Court
	Courts
	Cove
	Coves
	Creek
	Crescent
	Crest
	Crossing
	Crossroad
	Curve
	Dale
	Dam
	Divide
	Drive
	Drives
	Estate
	Estates
	Expressway
	Extension
	Extensions
	Fall
	Falls
	Ferry
	Field
	Fields
	Flat
	Flats
	Ford
	Fords
	Forest
	Forge
	Forges
	Fork
	Forks
	Fort
	Freeway
	Garden
	Gardens
	Gateway
	Glen
	Glens
	Green
	Greens
	Grov
	Grove
	Harbor
	Harbors
	Haven
	Heights
	Highway
	Hill
	Hills
	Hollow
	Inlet
	Island
	Islands
	Isle
	Junction
	Junctions
	Key
	Keys
	Knoll
	Knolls
	Lake
	Lakes
	Land
	Landing
	Lane
	Light
	Lights
	Loaf
	Lock
	Locks
	Lodge
	Loop
	Mall
	Manor
	Manors
	Meadow
	Meadows
	Mews
	Mill
	Mills
	Mission
	Motorway
	Mount
	Mountain
	Mountains
	Neck
	Orchard
	Oval
	Overpass
	Park
	Parkway
	Pass
	Passage
	Path
	Pike
	Pine
	Pines
	Place
	Plain
	Plains
	Plaza
	Point
	Points
	Port
	Ports
	Prairie
	Radial
	Ramp
	Ranch
	Rapid
	Rapids
	Rest
	Ridge
	Ridges
	River
	Road
	Roads
	Route
	Row
	Rue
	Run
	Shoal
	Shoals
	Shore
	Shores
	Skyway
	Spring
	Springs
	Spur
	Square
	Squares
	Station
	Stravenue
	Stream
	Street
	Streets
	Summit
	Terrace
	Throughway
	Trace
	Track
	Trafficway
	Trail
	Tunnel
	Turnpike
	Underpass
	Union
	Unions
	Valley
	Valleys
	Viaduct
	View
	Views
	Village
	Villages
	Ville
	Vista
	Walk
	Wall
	Way
	Ways
	Well
	Wells
	')]</value>
      <webElementGuid>da7d1e1c-fa46-4a1e-bcf6-66248352b5b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
