<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NO YES_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>3d6605ee-b1c5-4bc7-8498-d5149c03e76c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='flexApptInterview']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flexApptInterview</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a02e1f49-e368-4820-ba71-c4957e1764e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>flexApptInterview</value>
      <webElementGuid>cfe836c7-62f7-4550-bea1-682c6885c7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Are you conducting a flexible appointment interview now</value>
      <webElementGuid>3f10e8cc-c85a-4b6a-980a-d57d1c2a1c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>dfd31b05-775b-4642-9e69-51ba1cbd4ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flexApptInterview</value>
      <webElementGuid>7aca8802-4a51-4abf-8975-20734a8a3642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>214ad3aa-7584-475c-b16e-1cb164ffefdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form50</value>
      <webElementGuid>6974193e-a32f-451e-b099-b9e759315f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>Are you conducting a flexible appointment interview now</value>
      <webElementGuid>6611ada7-dbf2-4b95-a002-c9a325d69133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>flexApptInterview</value>
      <webElementGuid>165340ce-ecd9-4ce0-924d-6417fa41c70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>setProcessTLMTask();enableContactTypeQuestion();showRelevantForms();</value>
      <webElementGuid>5fe9c906-5e25-47c7-ba05-7e4845cdb974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>validateFlexAppointment(this)</value>
      <webElementGuid>686a5515-cb6e-4255-a7b2-132721637fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 
 NO
 YES
 </value>
      <webElementGuid>23a5e7a0-0be5-47c0-b9c6-b602ecc21622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flexApptInterview&quot;)</value>
      <webElementGuid>734215b6-9295-4084-ae24-7301cf0e0783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>17e47371-058b-497f-95ff-f929f7715b11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='flexApptInterview']</value>
      <webElementGuid>dcf79718-208e-46a0-bd03-aac227aca33b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you conducting a flexible appointment interview now?'])[1]/following::select[1]</value>
      <webElementGuid>5cef0836-ebc3-4102-aed9-374da9d7485e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is an appointment required or requested to process this application ?'])[1]/following::select[2]</value>
      <webElementGuid>c96defbe-bd2a-4cf0-aff6-d185b28ceb73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Was SNAP Requested??'])[1]/preceding::select[1]</value>
      <webElementGuid>9dce1cdb-3974-490d-b36d-17b682f41ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Type:'])[1]/preceding::select[2]</value>
      <webElementGuid>b620aab7-0e47-4125-94b6-245c23bed346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[18]/tbody/tr/td[2]/select</value>
      <webElementGuid>b189e3a8-4362-41bb-9a7a-31aed31c25e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'flexApptInterview' and @id = 'flexApptInterview' and (text() = '
 
 NO
 YES
 ' or . = '
 
 NO
 YES
 ')]</value>
      <webElementGuid>465004d3-cfeb-4630-aec7-c8e06c8083f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
