<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Unknown Male Female</name>
   <tag></tag>
   <elementGuidId>45c93c76-4c72-47fe-a886-4ba8948e292a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gender']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gender</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9ce34249-9793-4d0b-a654-c3fc64435a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>21ddb6cf-50fc-42ec-9e34-14714851e86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Gender</value>
      <webElementGuid>558121f1-7ade-4d95-bed9-e6ce459b22f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>0e550568-d13f-482c-8cd3-c1766ee6d7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>c2f4836b-936e-4717-a4d6-aab7720c5f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3c4429ed-575e-4ab2-8fe6-d51366b1613d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form100</value>
      <webElementGuid>6c286c96-c994-4727-8103-a260564c5b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>Gender</value>
      <webElementGuid>32e650af-6df0-486c-ae1d-6ef6d27fd819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>5ead0d5b-c111-493f-a466-c9d4246a8877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>callCheckGender();onChangeDOBdt();disableHTWTab(document.form1);</value>
      <webElementGuid>31a64e9f-3e20-4020-aed8-44be78474e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>checkMbccGender();checkARMbccGender();</value>
      <webElementGuid>b0d95126-7f47-4f50-a1d9-c0c56165e017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 Unknown
 Male
 Female
 </value>
      <webElementGuid>33514792-4c09-41ce-94f4-bb236640d9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gender&quot;)</value>
      <webElementGuid>47577f17-2777-4f94-b967-d471a6c16fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>c90874b8-5d6a-4d90-8dbb-f5cc3126ef31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gender']</value>
      <webElementGuid>1d8b0fef-50cb-47f3-b99c-40b6cfbef83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demographic Information'])[1]/following::select[1]</value>
      <webElementGuid>b3c399fd-84f5-4f35-ab1c-8acb83ac6a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth:'])[1]/preceding::select[1]</value>
      <webElementGuid>3e476014-7e1a-4f17-b335-ac7dd1cf0da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[14]/tbody/tr/td[2]/select</value>
      <webElementGuid>3ad56df2-172e-4755-8092-f75e2587472b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'gender' and @id = 'gender' and (text() = '
 Unknown
 Male
 Female
 ' or . = '
 Unknown
 Male
 Female
 ')]</value>
      <webElementGuid>1cf5d833-cf2f-43e8-acd2-b253002a2add</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
