<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_English Spanish Vietnamese Sign Lang_257107</name>
   <tag></tag>
   <elementGuidId>a32b3e23-8af5-4682-af34-0b4430da30db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='languages']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#languages</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4bd612e6-e9e4-4521-87e6-1d4ef916eb9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>languages</value>
      <webElementGuid>330c922a-10c3-4b4a-9182-43c5bd5b07ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Language(s)</value>
      <webElementGuid>0b7ebb30-f572-44d4-ae38-55d6ed8dddbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>449594bb-de61-49d6-a40c-878699e3384f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>languages</value>
      <webElementGuid>6b8b411a-34e3-4002-bb4e-380b94e77a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>bd718b3a-ebb6-4736-95e5-82713f088144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form150</value>
      <webElementGuid>73bcf6bf-9f5d-45a8-b00b-7b42cb4cd521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lbldesc</name>
      <type>Main</type>
      <value>Language(s)</value>
      <webElementGuid>36ba4d45-a678-42ce-ac8d-b968a31bd25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpid</name>
      <type>Main</type>
      <value>languages</value>
      <webElementGuid>2289ad25-089b-4eff-ab85-a96eb25763f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 English
 Spanish
 Vietnamese
 Sign Language
 Albanian
 Amharic
 Arabic
 Armenian
 Bengali
 Bosnian
 Chinese - Cantonese
 Chinese - Mandarin
 Croatian
 Czech
 Farsi
 French
 German
 Greek
 Haitian Creole
 Hebrew
 Hindi
 Hmong
 Hungarian
 Indonesian
 Italian
 Japanese
 Khmer
 Korean
 Kurdish
 Laotian
 Maltese
 Polish
 Portuguese
 Punjabi
 Russian
 Serbian
 Slovak
 Slovenian
 Somali
 Swahili
 Tagalog
 Taiwanese
 Thai
 Tigrinya
 Turkish
 Urdu
 Visayan
 Other
 </value>
      <webElementGuid>3c38c3b5-8349-48d5-8bfe-3d287cd89c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;languages&quot;)</value>
      <webElementGuid>7c5166a6-6e57-4465-8dfc-34e611ba4ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIERS_App_Reg/Page_Texas Integrated Eligibility Redesign System/iframe_My Alerts_bodyframe</value>
      <webElementGuid>08a5a9d6-2bf5-4d6b-9749-53e6ff214adc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='languages']</value>
      <webElementGuid>4a53c9d8-7ac1-4447-ab43-edd327635ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language(s):'])[1]/following::select[1]</value>
      <webElementGuid>313c85ce-43ff-4fc9-9be1-70560bff8d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHIP Client Id:'])[1]/following::select[1]</value>
      <webElementGuid>e1f4f602-aaa6-4ca9-bbff-3eae911c730f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other Information'])[1]/preceding::select[1]</value>
      <webElementGuid>8618db8e-8cd5-446d-9ac1-eb2e3d5ceafd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does the individual have other names?'])[1]/preceding::select[1]</value>
      <webElementGuid>392a52a7-ae36-4e92-b192-6f3b166e2491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/select</value>
      <webElementGuid>9b5fd008-498a-4e73-8a35-211605f200aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'languages' and @id = 'languages' and (text() = '
 English
 Spanish
 Vietnamese
 Sign Language
 Albanian
 Amharic
 Arabic
 Armenian
 Bengali
 Bosnian
 Chinese - Cantonese
 Chinese - Mandarin
 Croatian
 Czech
 Farsi
 French
 German
 Greek
 Haitian Creole
 Hebrew
 Hindi
 Hmong
 Hungarian
 Indonesian
 Italian
 Japanese
 Khmer
 Korean
 Kurdish
 Laotian
 Maltese
 Polish
 Portuguese
 Punjabi
 Russian
 Serbian
 Slovak
 Slovenian
 Somali
 Swahili
 Tagalog
 Taiwanese
 Thai
 Tigrinya
 Turkish
 Urdu
 Visayan
 Other
 ' or . = '
 English
 Spanish
 Vietnamese
 Sign Language
 Albanian
 Amharic
 Arabic
 Armenian
 Bengali
 Bosnian
 Chinese - Cantonese
 Chinese - Mandarin
 Croatian
 Czech
 Farsi
 French
 German
 Greek
 Haitian Creole
 Hebrew
 Hindi
 Hmong
 Hungarian
 Indonesian
 Italian
 Japanese
 Khmer
 Korean
 Kurdish
 Laotian
 Maltese
 Polish
 Portuguese
 Punjabi
 Russian
 Serbian
 Slovak
 Slovenian
 Somali
 Swahili
 Tagalog
 Taiwanese
 Thai
 Tigrinya
 Turkish
 Urdu
 Visayan
 Other
 ')]</value>
      <webElementGuid>eb1be489-e389-4edf-86cb-a363645f15c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
