<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Account</name>
   <tag></tag>
   <elementGuidId>0d813c9d-4311-4181-8a0c-ae1875e31959</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rso']/div/div/div/div/table/tbody/tr/td/div/h3/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.l</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>68325cb5-2adb-4e5c-b18e-2df2df541a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>l</value>
      <webElementGuid>437be2c2-8237-4adf-879e-1e0a75bdfd72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=&amp;ved=2ahUKEwjMjZ7hi9j8AhXNnWoFHX_9DooQjBB6BAgYEAE&amp;url=https%3A%2F%2Fwww.google.com%2Faccount%2Fabout%2F&amp;usg=AOvVaw1krdw1we7Jz4n3VKb0NMaF</value>
      <webElementGuid>3fd88371-93c8-439a-b3b4-c1652978e70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-jsarwt</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8a84ef2d-ec23-4189-95d5-79f4cd3d17a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-usg</name>
      <type>Main</type>
      <value>AOvVaw1krdw1we7Jz4n3VKb0NMaF</value>
      <webElementGuid>cd0e12ba-0567-459a-a107-ab71b7a2576f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ved</name>
      <type>Main</type>
      <value>2ahUKEwjMjZ7hi9j8AhXNnWoFHX_9DooQjBB6BAgYEAE</value>
      <webElementGuid>95fa1775-d37f-4524-8953-3f7e20adc548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctbtn</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8add5afa-29e0-48bd-85b7-489848e1ddc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cthref</name>
      <type>Main</type>
      <value>/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=&amp;ved=2ahUKEwjMjZ7hi9j8AhXNnWoFHX_9DooQjBB6BAgYEAE&amp;url=https%3A%2F%2Fwww.google.com%2Faccount%2Fabout%2F&amp;usg=AOvVaw1krdw1we7Jz4n3VKb0NMaF</value>
      <webElementGuid>06eef2af-1dba-4033-9f76-a581000fd2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-jrwt</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a9dcac76-0c81-4a81-9e79-3f3a90df58cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account</value>
      <webElementGuid>e3dedbc9-8405-44a3-ba44-4c659e14e52a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rso&quot;)/div[@class=&quot;hlcw0c&quot;]/div[@class=&quot;MjjYud&quot;]/div[@class=&quot;g&quot;]/div[@class=&quot;BYM4Nd&quot;]/table[@class=&quot;jmjoTe&quot;]/tbody[1]/tr[@class=&quot;mslg dmenKe&quot;]/td[@class=&quot;cIkxbf&quot;]/div[@class=&quot;usJj9c&quot;]/h3[1]/a[@class=&quot;l&quot;]</value>
      <webElementGuid>545e1b9b-7d02-492c-a084-f8aced160796</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rso']/div/div/div/div/table/tbody/tr/td/div/h3/a</value>
      <webElementGuid>5c69d151-5ce7-4249-ac65-34c89ec70c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Account')]</value>
      <webElementGuid>f2b321b3-dcf9-4b28-a682-ca22d4713384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google'])[2]/following::a[1]</value>
      <webElementGuid>a1a3fa97-fb0d-4aa3-9fff-1a717eb4c691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://www.google.com'])[2]/following::a[1]</value>
      <webElementGuid>48d403ae-6d25-441e-aa42-d6555d91463b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In your Google Account, you can see and manage your info ...'])[1]/preceding::a[1]</value>
      <webElementGuid>820c6b57-0b43-4a11-aed3-101b8541bb31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google Maps'])[1]/preceding::a[1]</value>
      <webElementGuid>6d3cdb51-dd8e-447f-be52-40be14c8bc5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Account']/parent::*</value>
      <webElementGuid>8d3a28c0-8a1a-4e08-8fc9-193f738467cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=&amp;ved=2ahUKEwjMjZ7hi9j8AhXNnWoFHX_9DooQjBB6BAgYEAE&amp;url=https%3A%2F%2Fwww.google.com%2Faccount%2Fabout%2F&amp;usg=AOvVaw1krdw1we7Jz4n3VKb0NMaF')]</value>
      <webElementGuid>28f3a60b-9990-4690-b588-b6bcd48fbe06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>3ce81ef9-e7a2-41be-907b-944e95676fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=&amp;ved=2ahUKEwjMjZ7hi9j8AhXNnWoFHX_9DooQjBB6BAgYEAE&amp;url=https%3A%2F%2Fwww.google.com%2Faccount%2Fabout%2F&amp;usg=AOvVaw1krdw1we7Jz4n3VKb0NMaF' and (text() = 'Account' or . = 'Account')]</value>
      <webElementGuid>9c481e9c-4420-4d59-95dc-21514626763a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=&amp;ved=2ahUKEwiD_qy_i9j8AhVQmWoFHecvAX0QjBB6BAgdEAE&amp;url=https%3A%2F%2Fwww.google.com%2Faccount%2Fabout%2F&amp;usg=AOvVaw1krdw1we7Jz4n3VKb0NMaF')]</value>
      <webElementGuid>466accf6-d595-407f-b724-cbbf0229c027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=&amp;ved=2ahUKEwiD_qy_i9j8AhVQmWoFHecvAX0QjBB6BAgdEAE&amp;url=https%3A%2F%2Fwww.google.com%2Faccount%2Fabout%2F&amp;usg=AOvVaw1krdw1we7Jz4n3VKb0NMaF' and (text() = 'Account' or . = 'Account')]</value>
      <webElementGuid>156bfb01-cfd0-4321-9a98-533aa6c80b18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
