<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Menu_searchbox-searchbutton</name>
   <tag></tag>
   <elementGuidId>da7ad0a3-da03-4e53-9375-8d2838ae213c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchbox-searchbutton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='searchbox-searchbutton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dfd88376-3090-49c5-95ec-5c29aa273ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jslog</name>
      <type>Main</type>
      <value>11887</value>
      <webElementGuid>475a2c59-a1b6-49ff-8cf5-b4a5f19c901d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>38eaa241-0fba-496f-92b4-6e2f98b2ff04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchbox-searchbutton</value>
      <webElementGuid>1b10426a-3dc4-45a9-a799-740f5d78ba4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jstcache</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>ffbefe09-e805-4a3d-9f0c-e17c4f1adbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>omnibox.search;mouseover:omnibox.showTooltip;mouseout:omnibox.hideTooltip;focus:omnibox.showTooltip;blur:omnibox.hideTooltip</value>
      <webElementGuid>58f08ae2-2898-4e98-8975-ba58cad4db06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mL3xi RR87W</value>
      <webElementGuid>3277d61b-4c9e-41d5-8c54-b04a083eef6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsan</name>
      <type>Main</type>
      <value>7.mL3xi,0.jslog,0.aria-label,0.id,22.jsaction</value>
      <webElementGuid>fd60ee5e-12a9-4492-8294-f09d9364ef70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchbox-searchbutton&quot;)</value>
      <webElementGuid>9a009b90-ccc6-4b6c-8ee5-a891c4d60932</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='searchbox-searchbutton']</value>
      <webElementGuid>c40eddad-f407-42e1-9c54-54776066259d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchbox']/div/button</value>
      <webElementGuid>462f39ca-ecda-44a1-8895-71cd8837e4ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>88dfff76-5b54-47ed-bdcd-8423fd0267f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'searchbox-searchbutton']</value>
      <webElementGuid>21a0db54-7617-461e-b3c6-207e63fe4561</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
