<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Google Maps_q</name>
   <tag></tag>
   <elementGuidId>ec6f9cdd-0894-4211-8482-5b88f39c54b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchboxinput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchboxinput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdeb4c2f-09d4-42ff-ad45-8c01bf64e753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jslog</name>
      <type>Main</type>
      <value>11886</value>
      <webElementGuid>dc23fb55-4fb8-4db4-9a2b-12c85b12f0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>ydp1wd-haAclf</value>
      <webElementGuid>1d23dccf-bdc2-4a92-be99-00b9584ea17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>08137a5a-3fb7-412b-a6af-d5f5f15cd7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
      <webElementGuid>f2c074cb-8e2c-43eb-919f-6f7dffcf37b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchboxinput</value>
      <webElementGuid>23c22023-9b9a-483f-98ed-d0845585ee07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>4dd78f3f-74b9-4b5c-b7d2-3324a4c27ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jstcache</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>fbbee2dd-cb30-4bfa-a4a0-88f3e5503463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>keyup:omnibox.keyUp;input:omnibox.inputDetected;keydown:omnibox.keyDown;focus:omnibox.focus;blur:omnibox.blur</value>
      <webElementGuid>d3d917dc-f8bc-436d-a142-473d7d72f600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchboxinput xiQnY</value>
      <webElementGuid>1b78e9cf-ad30-4114-bb17-7bdef477ebe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsan</name>
      <type>Main</type>
      <value>7.searchboxinput,7.xiQnY,0.jslog,0.aria-controls,0.autocomplete,0.autofocus,0.id,0.name,22.jsaction</value>
      <webElementGuid>c8fde254-166e-443d-8a72-4f181bca46e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchboxinput&quot;)</value>
      <webElementGuid>38c39ab6-0bd8-4538-ae8b-36ed011049df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchboxinput']</value>
      <webElementGuid>6d41cd50-d0c9-48a4-a627-1d9995adb29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='XmI62e']/input</value>
      <webElementGuid>1222b0bd-e9f2-4d57-a064-101c8a28cc6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3a505c0a-ffbd-41e5-aa6f-c0e11b25cc8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchboxinput' and @name = 'q']</value>
      <webElementGuid>01edbe97-c5ee-4296-86fb-df015c30aaeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
