<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Images_gb_Ze</name>
   <tag></tag>
   <elementGuidId>6c7c56fe-ffd8-4269-90db-655cff3ae6f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.gb_Ze</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Images'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>15dc458d-d7f6-4c12-ad61-5e7e4ff7a285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb_Ze</value>
      <webElementGuid>7190e8fa-3fe3-425d-b57c-ae7207334eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d44c7da0-265f-496e-bba1-efa92bef05ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>ec4bccc7-9646-48da-a84c-405c038478f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gbwa&quot;)/div[@class=&quot;gb_Df&quot;]/a[@class=&quot;gb_e&quot;]/svg[@class=&quot;gb_Ze&quot;]</value>
      <webElementGuid>380b44fc-a5d1-4026-ae51-10b65d977066</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Images'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>d2b3002d-db7b-4fda-8946-7afefccf5277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gmail'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>846231bb-13f2-4b1c-b53e-c63981defa71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>4ad0e7c9-d624-4cb9-86f7-37faf8c62f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>eb497e59-2ba2-4049-9ec0-c19dddd1216f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
